using System.Reflection;
using System.Text;

namespace Impulse.Validation;

/// <summary>
/// Generates Zod schemas from validation metadata.
/// </summary>
public sealed class ZodSchemaGenerator
{
    private readonly HashSet<string> _generatedSchemas = new();
    private readonly Dictionary<Type, string> _typeToSchemaName = new();

    /// <summary>
    /// Generates Zod schemas for all registered validators.
    /// </summary>
    public string Generate(IEnumerable<ValidatorMetadata> validators)
    {
        _generatedSchemas.Clear();
        _typeToSchemaName.Clear();

        var sb = new StringBuilder();
        sb.AppendLine("// This file is auto-generated by Impulse.Validation");
        sb.AppendLine("// Do not edit manually");
        sb.AppendLine();
        sb.AppendLine("import { z } from 'zod';");
        sb.AppendLine();

        // First pass: register all schema names
        foreach (var validator in validators)
        {
            var schemaName = ToCamelCase(validator.TypeName) + "Schema";
            _typeToSchemaName[validator.ValidatedType] = schemaName;
        }

        foreach (var validator in validators)
        {
            sb.AppendLine(GenerateSchema(validator));
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string GenerateSchema(ValidatorMetadata metadata)
    {
        var sb = new StringBuilder();
        var schemaName = ToCamelCase(metadata.TypeName) + "Schema";

        sb.AppendLine($"export const {schemaName} = z.object({{");

        foreach (var property in metadata.Properties)
        {
            var zodType = BuildZodType(property);
            sb.AppendLine($"  {ToCamelCase(property.Name)}: {zodType},");
        }

        sb.AppendLine("});");
        sb.AppendLine();
        sb.AppendLine($"export type {metadata.TypeName} = z.infer<typeof {schemaName}>;");

        return sb.ToString();
    }

    private static string BuildZodType(PropertyValidation property)
    {
        var baseType = GetZodBaseType(property.PropertyType);
        var chain = new StringBuilder(baseType);

        foreach (var rule in property.Rules)
        {
            var zodRule = ConvertRuleToZod(rule);
            if (!string.IsNullOrEmpty(zodRule))
            {
                chain.Append($".{zodRule}");
            }
        }

        if (property.IsNullable)
        {
            chain.Append(".nullable()");
        }

        if (property.IsOptional)
        {
            chain.Append(".optional()");
        }

        return chain.ToString();
    }

    private static string GetZodBaseType(Type type)
    {
        var underlyingType = Nullable.GetUnderlyingType(type) ?? type;

        if (underlyingType == typeof(string))
            return "z.string()";

        if (underlyingType == typeof(int) || underlyingType == typeof(long) ||
            underlyingType == typeof(short) || underlyingType == typeof(byte) ||
            underlyingType == typeof(double) || underlyingType == typeof(float) ||
            underlyingType == typeof(decimal))
            return "z.number()";

        if (underlyingType == typeof(bool))
            return "z.boolean()";

        if (underlyingType == typeof(DateTime) || underlyingType == typeof(DateTimeOffset) ||
            underlyingType == typeof(DateOnly))
            return "z.string()"; // Dates as ISO strings

        if (underlyingType == typeof(Guid))
            return "z.string().uuid()";

        if (underlyingType.IsEnum)
        {
            var values = Enum.GetNames(underlyingType)
                .Select(n => $"'{ToCamelCase(n)}'");
            return $"z.enum([{string.Join(", ", values)}])";
        }

        if (underlyingType.IsArray || (underlyingType.IsGenericType &&
            typeof(System.Collections.IEnumerable).IsAssignableFrom(underlyingType)))
        {
            var elementType = underlyingType.IsArray
                ? underlyingType.GetElementType()!
                : underlyingType.GetGenericArguments().FirstOrDefault() ?? typeof(object);
            return $"z.array({GetZodBaseType(elementType)})";
        }

        // Handle nested complex types (classes/records)
        if (underlyingType.IsClass && underlyingType != typeof(object))
        {
            // Reference existing schema if available
            var schemaName = ToCamelCase(underlyingType.Name) + "Schema";
            return schemaName;
        }

        return "z.unknown()";
    }

    private static string? ConvertRuleToZod(ValidationRule rule)
    {
        return rule.Type switch
        {
            ValidationRuleType.NotEmpty => "min(1)",
            ValidationRuleType.NotNull => "min(1)",
            ValidationRuleType.MaxLength when rule.Parameters.TryGetValue("max", out var max) => $"max({max})",
            ValidationRuleType.MinLength when rule.Parameters.TryGetValue("min", out var min) => $"min({min})",
            ValidationRuleType.Email => "email()",
            ValidationRuleType.GreaterThan when rule.Parameters.TryGetValue("value", out var val) => $"gt({val})",
            ValidationRuleType.LessThan when rule.Parameters.TryGetValue("value", out var val) => $"lt({val})",
            ValidationRuleType.GreaterThanOrEqual when rule.Parameters.TryGetValue("value", out var val) => $"gte({val})",
            ValidationRuleType.LessThanOrEqual when rule.Parameters.TryGetValue("value", out var val) => $"lte({val})",
            ValidationRuleType.Regex when rule.Parameters.TryGetValue("pattern", out var pattern) => $"regex(/{pattern}/)",
            ValidationRuleType.Url => "url()",
            _ => null // Server-only rules
        };
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;

        return char.ToLowerInvariant(name[0]) + name[1..];
    }
}

/// <summary>
/// Metadata about a validator.
/// </summary>
public sealed class ValidatorMetadata
{
    public required string TypeName { get; init; }
    public required Type ValidatedType { get; init; }
    public List<PropertyValidation> Properties { get; } = new();
}

/// <summary>
/// Validation metadata for a property.
/// </summary>
public sealed class PropertyValidation
{
    public required string Name { get; init; }
    public required Type PropertyType { get; init; }
    public bool IsNullable { get; init; }
    public bool IsOptional { get; init; }
    public List<ValidationRule> Rules { get; } = new();
}

/// <summary>
/// A single validation rule.
/// </summary>
public sealed class ValidationRule
{
    public required ValidationRuleType Type { get; init; }
    public Dictionary<string, object> Parameters { get; } = new();
}

/// <summary>
/// Types of validation rules that can be mapped to Zod.
/// </summary>
public enum ValidationRuleType
{
    NotEmpty,
    NotNull,
    MaxLength,
    MinLength,
    Email,
    GreaterThan,
    LessThan,
    GreaterThanOrEqual,
    LessThanOrEqual,
    Regex,
    Url,
    Custom // Server-only
}
