using System.Text;
using Impulse.SourceGen.Ast;

namespace Impulse.SourceGen.Emitters;

/// <summary>
/// Emits TanStack Router routes, loaders, and mutations from RouteNode AST.
/// </summary>
public class RouteEmitter
{
    private readonly StringBuilder _sb = new();
    private int _indent;
    private const string IndentString = "  ";

    /// <summary>
    /// Emit the RoutePaths constant file.
    /// </summary>
    public string EmitRoutePaths(RouteFile routes)
    {
        _sb.Clear();
        AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        AppendLine();
        AppendLine("/**");
        AppendLine(" * Type-safe route path constants.");
        AppendLine(" * Use these for Link components and navigation.");
        AppendLine(" */");
        AppendLine("export const RoutePaths = {");
        _indent++;

        foreach (var route in routes.Routes)
        {
            var key = route.Name.Replace("Endpoint", "");
            AppendLine($"{key}: '{route.Path}' as const,");
        }

        _indent--;
        AppendLine("} as const;");
        AppendLine();
        AppendLine("export type RoutePath = typeof RoutePaths[keyof typeof RoutePaths];");

        return _sb.ToString();
    }

    /// <summary>
    /// Emit the virtual TanStack Router routes file.
    /// </summary>
    public string EmitVirtualRoutes(RouteFile routes)
    {
        _sb.Clear();
        var queryEndpoints = routes.Routes.Where(r => r.IsQuery).ToList();

        AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        AppendLine("// Virtual file routes for TanStack Router");
        AppendLine("import { createRoute, createRootRoute, createRouter } from '@tanstack/react-router';");
        AppendLine("import { RoutePaths } from './routePaths';");

        // Import response types
        var responseTypes = queryEndpoints
            .Where(e => e.ResponseType != null)
            .Select(e => e.ResponseType!)
            .Distinct()
            .ToList();

        if (responseTypes.Count > 0)
        {
            AppendLine($"import type {{ {string.Join(", ", responseTypes)} }} from './types';");
        }

        AppendLine();
        AppendLine("// Context type for impulse loader");
        AppendLine("interface ImpulseContext {");
        _indent++;
        AppendLine("impulse: <T>(url: string) => Promise<T>;");
        _indent--;
        AppendLine("}");
        AppendLine();

        // Root route
        AppendLine("// Root route");
        AppendLine("export const rootRoute = createRootRoute();");
        AppendLine();

        // Individual route definitions
        foreach (var route in queryEndpoints)
        {
            EmitRouteDefinition(route);
        }

        // Route tree
        AppendLine("// Route tree - add all routes as children of root");
        AppendLine("export const routeTree = rootRoute.addChildren([");
        _indent++;
        foreach (var route in queryEndpoints)
        {
            var varName = ToCamelCase(route.Name.Replace("Endpoint", "")) + "Route";
            AppendLine($"{varName},");
        }
        _indent--;
        AppendLine("]);");
        AppendLine();

        // Router instance
        AppendLine("// Create the router instance");
        AppendLine("export const router = createRouter({ routeTree });");
        AppendLine();

        // Routes object
        EmitRoutesObject(queryEndpoints);

        // Path builders
        AppendLine("// Type-safe path builders");
        foreach (var route in queryEndpoints)
        {
            if (route.HasParameters)
            {
                EmitPathBuilder(route);
            }
        }

        return _sb.ToString();
    }

    private void EmitRouteDefinition(RouteDefinition route)
    {
        var routeName = route.Name.Replace("Endpoint", "");
        var varName = ToCamelCase(routeName) + "Route";
        var tanstackPath = route.Path.Replace("{", "$").Replace("}", "");

        AppendLine($"export const {varName} = createRoute({{");
        _indent++;
        AppendLine("getParentRoute: () => rootRoute,");
        AppendLine($"path: '{tanstackPath}',");

        if (route.ResponseType != null)
        {
            AppendLine("loader: async ({ context, params }) => {");
            _indent++;
            AppendLine("const ctx = context as ImpulseContext;");

            if (route.HasParameters)
            {
                AppendLine($"let url: string = RoutePaths.{routeName};");
                foreach (var param in route.Parameters)
                {
                    AppendLine($"url = url.replace('{{{param.Name}}}', params.{param.Name});");
                }
                AppendLine($"return ctx.impulse<{route.ResponseType}>(url);");
            }
            else
            {
                AppendLine($"return ctx.impulse<{route.ResponseType}>(RoutePaths.{routeName});");
            }

            _indent--;
            AppendLine("},");
        }

        // Emit deferred loaders if any
        if (route.Deferred.Count > 0)
        {
            AppendLine("deferred: {");
            _indent++;
            foreach (var deferred in route.Deferred)
            {
                AppendLine($"{deferred.Key}: async ({{ context, params }}) => {{");
                _indent++;
                AppendLine("const ctx = context as ImpulseContext;");
                var deferredPath = deferred.Path;
                foreach (var param in route.Parameters)
                {
                    deferredPath = deferredPath.Replace($"{{{param.Name}}}", $"${{params.{param.Name}}}");
                }
                AppendLine($"return ctx.impulse<{deferred.ResponseType}>(`{deferredPath}`);");
                _indent--;
                AppendLine("},");
            }
            _indent--;
            AppendLine("},");
        }

        _indent--;
        AppendLine("});");
        AppendLine();
    }

    private void EmitRoutesObject(List<RouteDefinition> routes)
    {
        AppendLine("// Route definitions object for programmatic access");
        AppendLine("export const routes = {");
        _indent++;

        foreach (var route in routes)
        {
            var routeName = route.Name.Replace("Endpoint", "");
            var routeKey = ToCamelCase(routeName);

            AppendLine($"{routeKey}: {{");
            _indent++;
            AppendLine($"path: '{route.Path}' as const,");
            AppendLine($"method: 'GET' as const,");
            AppendLine($"loader: RoutePaths.{routeName},");
            _indent--;
            AppendLine("},");
        }

        _indent--;
        AppendLine("} as const;");
        AppendLine();
    }

    private void EmitPathBuilder(RouteDefinition route)
    {
        var routeName = route.Name.Replace("Endpoint", "");
        var funcName = ToCamelCase(routeName) + "Path";
        var paramsSignature = string.Join(", ",
            route.Parameters.Select(p => $"{p.Name}: string | number"));

        AppendLine($"export function {funcName}({paramsSignature}) {{");
        _indent++;

        // Build template literal
        var path = route.Path;
        foreach (var param in route.Parameters)
        {
            path = path.Replace($"{{{param.Name}}}", $"${{{param.Name}}}");
        }
        AppendLine($"return `{path}` as const;");

        _indent--;
        AppendLine("}");
    }

    /// <summary>
    /// Emit the loaders file.
    /// </summary>
    public string EmitLoaders(RouteFile routes)
    {
        _sb.Clear();
        var queryEndpoints = routes.Routes.Where(r => r.IsQuery && r.ResponseType != null).ToList();

        AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        AppendLine("import type { ImpulseContext } from '@impulse/react';");
        AppendLine("import { RoutePaths } from './routePaths';");
        AppendLine("import * as Types from './types';");
        AppendLine();
        AppendLine("/**");
        AppendLine(" * Type-safe loader functions for GET endpoints.");
        AppendLine(" * Use these in your route loaders.");
        AppendLine(" */");
        AppendLine("export const Loaders = {");
        _indent++;

        foreach (var route in queryEndpoints)
        {
            EmitLoader(route);
        }

        _indent--;
        AppendLine("} as const;");

        return _sb.ToString();
    }

    private void EmitLoader(RouteDefinition route)
    {
        var name = route.Name.Replace("Endpoint", "");
        var responseName = route.ResponseType!;

        AppendLine($"/** GET {route.Path} */");

        if (route.HasParameters)
        {
            var paramsType = string.Join(", ",
                route.Parameters.Select(p => $"{p.Name}: string"));

            AppendLine($"{name}: async (ctx: ImpulseContext, params: {{ {paramsType} }}): Promise<Types.{responseName}> => {{");
            _indent++;
            AppendLine($"let url: string = RoutePaths.{name};");
            foreach (var param in route.Parameters)
            {
                AppendLine($"url = url.replace('{{{param.Name}}}', params.{param.Name});");
            }
            AppendLine($"return ctx.impulse<Types.{responseName}>(url);");
            _indent--;
        }
        else
        {
            AppendLine($"{name}: async (ctx: ImpulseContext): Promise<Types.{responseName}> => {{");
            _indent++;
            AppendLine($"return ctx.impulse<Types.{responseName}>(RoutePaths.{name});");
            _indent--;
        }

        AppendLine("},");
        AppendLine();
    }

    /// <summary>
    /// Emit the mutations file.
    /// </summary>
    public string EmitMutations(RouteFile routes)
    {
        _sb.Clear();
        var mutationEndpoints = routes.Routes.Where(r => r.IsMutation && r.RequestType != null).ToList();

        AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        AppendLine("import { useMutation } from '@tanstack/react-query';");
        AppendLine("import { useRouter } from '@tanstack/react-router';");
        AppendLine("import type { ImpulseContext } from '@impulse/react';");
        AppendLine("import { RoutePaths } from './routePaths';");
        AppendLine("import * as Types from './types';");
        AppendLine("import * as Schemas from './validation';");
        AppendLine();

        foreach (var route in mutationEndpoints)
        {
            EmitMutation(route);
        }

        return _sb.ToString();
    }

    private void EmitMutation(RouteDefinition route)
    {
        var name = route.Name.Replace("Endpoint", "");
        var requestName = route.RequestType!;
        var responseName = route.ResponseType ?? "void";
        var schemaName = $"{requestName}Schema";
        var httpMethod = route.Method.ToString().ToUpperInvariant();

        AppendLine("/**");
        AppendLine($" * Mutation hook for {name}");
        AppendLine($" * {httpMethod} {route.Path}");
        AppendLine(" */");
        AppendLine($"export function use{name}Mutation(ctx: ImpulseContext) {{");
        _indent++;
        AppendLine("const router = useRouter();");
        AppendLine();
        AppendLine("return useMutation({");
        _indent++;
        AppendLine($"mutationFn: async (data: Types.{requestName}) => {{");
        _indent++;
        AppendLine("// Validate with Zod before sending");
        AppendLine($"const validated = Schemas.{schemaName}.parse(data);");
        AppendLine($"return ctx.impulseMutate<Types.{requestName}, Types.{responseName}>(");
        _indent++;
        AppendLine($"RoutePaths.{name},");
        AppendLine("validated,");
        AppendLine($"'{httpMethod}'");
        _indent--;
        AppendLine(");");
        _indent--;
        AppendLine("},");
        AppendLine("onSuccess: async () => {");
        _indent++;
        AppendLine("// Invalidate and refetch related queries");
        AppendLine("await router.invalidate();");
        _indent--;
        AppendLine("},");
        _indent--;
        AppendLine("});");
        _indent--;
        AppendLine("}");
        AppendLine();
    }

    private void Append(string text)
    {
        _sb.Append(new string(' ', _indent * IndentString.Length));
        _sb.Append(text);
    }

    private void AppendLine(string text = "")
    {
        if (string.IsNullOrEmpty(text))
        {
            _sb.AppendLine();
        }
        else
        {
            _sb.Append(new string(' ', _indent * IndentString.Length));
            _sb.AppendLine(text);
        }
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
