using System.Text;
using Impulse.SourceGen.Ast;

namespace Impulse.SourceGen.Emitters;

/// <summary>
/// Emits Zod validation schema code from ZodNode AST.
/// </summary>
public class ZodEmitter
{
    private readonly StringBuilder _sb = new();
    private int _indent;
    private const string IndentString = "  ";

    public string Emit(ZodFile file)
    {
        _sb.Clear();
        _indent = 0;

        // Add imports
        AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        AppendLine("import { z } from 'zod';");

        // Import enums from types.ts
        var enums = CollectEnumReferences(file.Schemas);
        if (enums.Count > 0)
        {
            AppendLine($"import {{ {string.Join(", ", enums)} }} from './types';");
        }
        AppendLine();

        // Topologically sort schemas so dependencies come first
        var sortedSchemas = TopologicalSort(file.Schemas);

        foreach (var schema in sortedSchemas)
        {
            EmitSchema(schema);
            AppendLine();
        }

        return _sb.ToString().TrimEnd();
    }

    /// <summary>
    /// Collect all enum names referenced in schemas for import.
    /// </summary>
    private HashSet<string> CollectEnumReferences(IReadOnlyList<ZodSchema> schemas)
    {
        var enums = new HashSet<string>();
        foreach (var schema in schemas)
        {
            CollectEnumsFromType(schema.Shape, enums);
        }
        return enums;
    }

    private void CollectEnumsFromType(ZodType type, HashSet<string> enums)
    {
        switch (type)
        {
            case ZodNativeEnum ne:
                enums.Add(ne.EnumName);
                break;
            case ZodObject obj:
                foreach (var prop in obj.Properties)
                    CollectEnumsFromType(prop.Type, enums);
                break;
            case ZodArray arr:
                CollectEnumsFromType(arr.Element, enums);
                break;
            case ZodOptional opt:
                CollectEnumsFromType(opt.Inner, enums);
                break;
            case ZodNullable nul:
                CollectEnumsFromType(nul.Inner, enums);
                break;
            case ZodUnion union:
                foreach (var t in union.Types)
                    CollectEnumsFromType(t, enums);
                break;
        }
    }

    /// <summary>
    /// Topological sort: emit schemas that are dependencies before those that depend on them.
    /// </summary>
    private List<ZodSchema> TopologicalSort(IReadOnlyList<ZodSchema> schemas)
    {
        var schemaByName = schemas.ToDictionary(s => s.Name);
        var visited = new HashSet<string>();
        var result = new List<ZodSchema>();

        void Visit(ZodSchema schema)
        {
            if (visited.Contains(schema.Name)) return;
            visited.Add(schema.Name);

            // Visit dependencies first
            var deps = GetSchemaReferences(schema.Shape);
            foreach (var dep in deps)
            {
                if (schemaByName.TryGetValue(dep, out var depSchema))
                    Visit(depSchema);
            }

            result.Add(schema);
        }

        foreach (var schema in schemas)
            Visit(schema);

        return result;
    }

    /// <summary>
    /// Get all ZodRef schema names from a type.
    /// </summary>
    private HashSet<string> GetSchemaReferences(ZodType type)
    {
        var refs = new HashSet<string>();
        CollectRefs(type, refs);
        return refs;
    }

    private void CollectRefs(ZodType type, HashSet<string> refs)
    {
        switch (type)
        {
            case ZodRef r:
                refs.Add(r.SchemaName);
                break;
            case ZodObject obj:
                foreach (var prop in obj.Properties)
                    CollectRefs(prop.Type, refs);
                break;
            case ZodArray arr:
                CollectRefs(arr.Element, refs);
                break;
            case ZodOptional opt:
                CollectRefs(opt.Inner, refs);
                break;
            case ZodNullable nul:
                CollectRefs(nul.Inner, refs);
                break;
            case ZodUnion union:
                foreach (var t in union.Types)
                    CollectRefs(t, refs);
                break;
        }
    }

    private void EmitSchema(ZodSchema schema)
    {
        Append($"export const {schema.Name} = ");
        EmitType(schema.Shape);
        _sb.AppendLine(";");
    }

    public void EmitType(ZodType type)
    {
        switch (type)
        {
            case ZodObject obj:
                EmitObject(obj);
                break;

            case ZodString str:
                _sb.Append("z.string()");
                EmitValidators(str.Validators);
                break;

            case ZodNumber num:
                _sb.Append("z.number()");
                EmitValidators(num.Validators);
                break;

            case ZodBoolean:
                _sb.Append("z.boolean()");
                break;

            case ZodDate:
                _sb.Append("z.date()");
                break;

            case ZodArray arr:
                _sb.Append("z.array(");
                EmitType(arr.Element);
                _sb.Append(')');
                EmitValidators(arr.Validators);
                break;

            case ZodRecord rec:
                _sb.Append("z.record(");
                EmitType(rec.Key);
                _sb.Append(", ");
                EmitType(rec.Value);
                _sb.Append(')');
                break;

            case ZodEnum ze:
                _sb.Append("z.enum([");
                _sb.Append(string.Join(", ", ze.Values.Select(v => $"'{v}'")));
                _sb.Append("])");
                break;

            case ZodNativeEnum ne:
                _sb.Append($"z.nativeEnum({ne.EnumName})");
                break;

            case ZodUnion union:
                _sb.Append("z.union([");
                for (var i = 0; i < union.Types.Count; i++)
                {
                    if (i > 0) _sb.Append(", ");
                    EmitType(union.Types[i]);
                }
                _sb.Append("])");
                break;

            case ZodIntersection inter:
                EmitType(inter.Left);
                _sb.Append(".and(");
                EmitType(inter.Right);
                _sb.Append(')');
                break;

            case ZodLiteral lit:
                _sb.Append($"z.literal({lit.Value})");
                break;

            case ZodNull:
                _sb.Append("z.null()");
                break;

            case ZodUndefined:
                _sb.Append("z.undefined()");
                break;

            case ZodUnknown:
                _sb.Append("z.unknown()");
                break;

            case ZodAny:
                _sb.Append("z.any()");
                break;

            case ZodTuple tuple:
                _sb.Append("z.tuple([");
                for (var i = 0; i < tuple.Elements.Count; i++)
                {
                    if (i > 0) _sb.Append(", ");
                    EmitType(tuple.Elements[i]);
                }
                _sb.Append("])");
                break;

            case ZodRef r:
                _sb.Append(r.SchemaName);
                break;

            case ZodNullable nullable:
                EmitType(nullable.Inner);
                _sb.Append(".nullable()");
                break;

            case ZodOptional optional:
                EmitType(optional.Inner);
                _sb.Append(".optional()");
                break;

            case ZodDefault def:
                EmitType(def.Inner);
                _sb.Append($".default({def.DefaultValue})");
                break;
        }
    }

    private void EmitObject(ZodObject obj)
    {
        if (obj.Properties.Count == 0)
        {
            _sb.Append("z.object({})");
            return;
        }

        _sb.AppendLine("z.object({");
        _indent++;
        for (var i = 0; i < obj.Properties.Count; i++)
        {
            var prop = obj.Properties[i];
            Append($"{prop.Name}: ");
            EmitType(prop.Type);
            if (prop.Optional)
            {
                _sb.Append(".optional()");
            }
            _sb.AppendLine(",");
        }
        _indent--;
        Append("})");
    }

    private void EmitValidators(IReadOnlyList<ZodValidator> validators)
    {
        foreach (var validator in validators)
        {
            EmitValidator(validator);
        }
    }

    private void EmitValidator(ZodValidator validator)
    {
        switch (validator)
        {
            case ZodMin min:
                _sb.Append($".min({min.Value}");
                EmitMessage(min.Message);
                _sb.Append(')');
                break;

            case ZodMax max:
                _sb.Append($".max({max.Value}");
                EmitMessage(max.Message);
                _sb.Append(')');
                break;

            case ZodLength len:
                _sb.Append($".length({len.Value}");
                EmitMessage(len.Message);
                _sb.Append(')');
                break;

            case ZodEmail email:
                _sb.Append(".email(");
                if (email.Message != null)
                {
                    _sb.Append($"'{email.Message}'");
                }
                _sb.Append(')');
                break;

            case ZodUrl url:
                _sb.Append(".url(");
                if (url.Message != null)
                {
                    _sb.Append($"'{url.Message}'");
                }
                _sb.Append(')');
                break;

            case ZodUuid uuid:
                _sb.Append(".uuid(");
                if (uuid.Message != null)
                {
                    _sb.Append($"'{uuid.Message}'");
                }
                _sb.Append(')');
                break;

            case ZodRegex regex:
                _sb.Append($".regex(/{regex.Pattern}/");
                EmitMessage(regex.Message);
                _sb.Append(')');
                break;

            case ZodInt zi:
                _sb.Append(".int(");
                if (zi.Message != null)
                {
                    _sb.Append($"'{zi.Message}'");
                }
                _sb.Append(')');
                break;

            case ZodPositive pos:
                _sb.Append(".positive(");
                if (pos.Message != null)
                {
                    _sb.Append($"'{pos.Message}'");
                }
                _sb.Append(')');
                break;

            case ZodNegative neg:
                _sb.Append(".negative(");
                if (neg.Message != null)
                {
                    _sb.Append($"'{neg.Message}'");
                }
                _sb.Append(')');
                break;

            case ZodNonnegative nn:
                _sb.Append(".nonnegative(");
                if (nn.Message != null)
                {
                    _sb.Append($"'{nn.Message}'");
                }
                _sb.Append(')');
                break;

            case ZodNonpositive np:
                _sb.Append(".nonpositive(");
                if (np.Message != null)
                {
                    _sb.Append($"'{np.Message}'");
                }
                _sb.Append(')');
                break;

            case ZodNonempty ne:
                _sb.Append(".nonempty(");
                if (ne.Message != null)
                {
                    _sb.Append($"'{ne.Message}'");
                }
                _sb.Append(')');
                break;

            case ZodDatetime dt:
                _sb.Append(".datetime(");
                if (dt.Message != null)
                {
                    _sb.Append($"'{dt.Message}'");
                }
                _sb.Append(')');
                break;

            case ZodTrim:
                _sb.Append(".trim()");
                break;

            case ZodLowerCase:
                _sb.Append(".toLowerCase()");
                break;

            case ZodUpperCase:
                _sb.Append(".toUpperCase()");
                break;

            case ZodStartsWith sw:
                _sb.Append($".startsWith('{sw.Prefix}'");
                EmitMessage(sw.Message);
                _sb.Append(')');
                break;

            case ZodEndsWith ew:
                _sb.Append($".endsWith('{ew.Suffix}'");
                EmitMessage(ew.Message);
                _sb.Append(')');
                break;

            case ZodIncludes inc:
                _sb.Append($".includes('{inc.Substring}'");
                EmitMessage(inc.Message);
                _sb.Append(')');
                break;

            case ZodMultipleOf mo:
                _sb.Append($".multipleOf({mo.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)}");
                EmitMessage(mo.Message);
                _sb.Append(')');
                break;

            case ZodFinite fin:
                _sb.Append(".finite(");
                if (fin.Message != null)
                {
                    _sb.Append($"'{fin.Message}'");
                }
                _sb.Append(')');
                break;

            case ZodSafe safe:
                _sb.Append(".safe(");
                if (safe.Message != null)
                {
                    _sb.Append($"'{safe.Message}'");
                }
                _sb.Append(')');
                break;
        }
    }

    private void EmitMessage(string? message)
    {
        if (message != null)
        {
            _sb.Append($", '{message}'");
        }
    }

    private void Append(string text)
    {
        _sb.Append(new string(' ', _indent * IndentString.Length));
        _sb.Append(text);
    }

    private void AppendLine(string text = "")
    {
        if (string.IsNullOrEmpty(text))
        {
            _sb.AppendLine();
        }
        else
        {
            _sb.Append(new string(' ', _indent * IndentString.Length));
            _sb.AppendLine(text);
        }
    }
}
