using System.Text;
using System.Text.RegularExpressions;

namespace Shalimar.Razor;

/// <summary>
/// TSX emitter that transforms Razor source into React TSX code.
///
/// Key transformations:
/// - class → className
/// - for → htmlFor
/// - @Props.X → {props.X}
/// - @if (cond) { } → {cond && ( )}
/// - @foreach (var x in xs) { } → {xs.map(x => ( ))}
/// - @onclick → onClick
/// </summary>
public class TsxEmitter
{
    private readonly string _fileName;
    private string _componentName;
    private string? _propsTypeName;
    private readonly HashSet<string> _childComponents = new();

    public TsxEmitter(string fileName)
    {
        _fileName = fileName;
        _componentName = Path.GetFileNameWithoutExtension(fileName);
    }

    public string Emit(string razorSource)
    {
        // Extract metadata
        ExtractMetadata(razorSource);

        var sb = new StringBuilder();

        // Header comment
        sb.AppendLine("// Generated by Shalimar.Razor - DO NOT EDIT");
        sb.AppendLine("import React from 'react';");

        // Child component imports
        foreach (var comp in _childComponents.OrderBy(c => c))
        {
            sb.AppendLine($"import {{ {comp} }} from './{comp}';");
        }

        sb.AppendLine();

        // Props interface
        if (_propsTypeName != null)
        {
            sb.AppendLine($"export interface {_propsTypeName} {{");
            var props = ExtractPropsUsage(razorSource);
            foreach (var prop in props)
            {
                sb.AppendLine($"  {prop}: any;");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Component function
        var propsParam = _propsTypeName != null ? $"props: {_propsTypeName}" : "";
        sb.AppendLine($"export function {_componentName}({propsParam}) {{");
        sb.AppendLine("  return (");

        // Transform the markup
        var jsx = TransformToJsx(razorSource);
        sb.Append(jsx);

        sb.AppendLine("  );");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void ExtractMetadata(string source)
    {
        // Extract props type from @inherits
        var inheritsMatch = Regex.Match(source, @"@inherits\s+SliceComponent<(\w+)>");
        if (inheritsMatch.Success)
        {
            _propsTypeName = inheritsMatch.Groups[1].Value;
        }

        // Find child components (PascalCase tags)
        var componentMatches = Regex.Matches(source, @"<([A-Z][a-zA-Z0-9]*)\s");
        foreach (Match match in componentMatches)
        {
            var name = match.Groups[1].Value;
            if (!IsHtmlElement(name))
            {
                _childComponents.Add(name);
            }
        }
    }

    private HashSet<string> ExtractPropsUsage(string source)
    {
        var props = new HashSet<string>();
        var matches = Regex.Matches(source, @"Props\.(\w+)");
        foreach (Match match in matches)
        {
            props.Add(match.Groups[1].Value);
        }
        return props;
    }

    private string TransformToJsx(string source)
    {
        var result = source;

        // Remove @inherits directive
        result = Regex.Replace(result, @"@inherits[^\n]+\n?", "");

        // Transform class → className (handle interpolated values)
        result = Regex.Replace(result, @"class=""([^""]*?)@Props\.(\w+)([^""]*?)""",
            m => $"className={{`{m.Groups[1].Value}${{props.{m.Groups[2].Value}}}{m.Groups[3].Value}`}}");
        result = Regex.Replace(result, @"class=""([^""]+)""", "className=\"$1\"");

        // Transform for → htmlFor
        result = Regex.Replace(result, @"\sfor=""([^""]+)""", " htmlFor=\"$1\"");

        // Transform @onclick with Props reference → onClick={props.X}
        result = Regex.Replace(result, @"@onclick=""@Props\.(\w+)""", "onClick={props.$1}");
        result = Regex.Replace(result, @"@onclick=""@(\w+)""", "onClick={$1}");

        // Transform @onchange → onChange
        result = Regex.Replace(result, @"@onchange=""@Props\.(\w+)""", "onChange={props.$1}");
        result = Regex.Replace(result, @"@onchange=""@(\w+)""", "onChange={$1}");

        // Transform disabled="@Props.X" → disabled={props.X}
        result = Regex.Replace(result, @"disabled=""@Props\.(\w+)""", "disabled={props.$1}");

        // Transform attribute props: Attr="@Props.X" → Attr={props.X}
        result = Regex.Replace(result, @"(\w+)=""@Props\.(\w+)""", "$1={props.$2}");

        // Transform @if blocks BEFORE other transformations
        result = TransformIfBlocks(result);

        // Transform @foreach blocks
        result = TransformForeachBlocks(result);

        // Transform remaining @Props.X → {props.X}
        result = Regex.Replace(result, @"@Props\.(\w+)", "{props.$1}");

        // Clean up any remaining C# string methods
        result = Regex.Replace(result, @"!string\.IsNullOrEmpty\(props\.(\w+)\)", "props.$1");
        result = Regex.Replace(result, @"string\.IsNullOrEmpty\(props\.(\w+)\)", "!props.$1");

        // Remove @else blocks (simplified - just remove them for now)
        result = Regex.Replace(result, @"\s*else\s*\{[^}]*\}", "", RegexOptions.Singleline);

        // Indent properly
        var lines = result.Trim().Split('\n');
        var sb = new StringBuilder();
        foreach (var line in lines)
        {
            var trimmed = line.Trim();
            if (!string.IsNullOrEmpty(trimmed))
            {
                sb.AppendLine("    " + trimmed);
            }
        }

        return sb.ToString();
    }

    private string TransformIfBlocks(string source)
    {
        var result = source;

        // Handle @if with balanced parentheses for condition
        while (true)
        {
            var ifIndex = result.IndexOf("@if");
            if (ifIndex == -1) break;

            // Find the opening paren
            var parenStart = result.IndexOf('(', ifIndex);
            if (parenStart == -1) break;

            // Extract balanced condition
            var condition = ExtractBalancedParens(result, parenStart);
            var afterCondition = parenStart + condition.Length + 2; // +2 for parens

            // Find opening brace
            var braceStart = result.IndexOf('{', afterCondition);
            if (braceStart == -1) break;

            // Extract balanced content
            var content = ExtractBalancedBraces(result, braceStart);
            var endIndex = braceStart + content.Length + 2; // +2 for braces

            // Transform condition
            var transformedCondition = TransformCondition(condition);
            var replacement = $"{{({transformedCondition}) && (\n{content.Trim()}\n)}}";

            result = result.Substring(0, ifIndex) + replacement + result.Substring(endIndex);
        }

        return result;
    }

    private string ExtractBalancedParens(string source, int openParenIndex)
    {
        var depth = 1;
        var i = openParenIndex + 1;
        while (i < source.Length && depth > 0)
        {
            if (source[i] == '(') depth++;
            else if (source[i] == ')') depth--;
            i++;
        }
        return source.Substring(openParenIndex + 1, i - openParenIndex - 2);
    }

    private string TransformForeachBlocks(string source)
    {
        var result = source;

        // Handle @foreach with nested braces
        while (Regex.IsMatch(result, @"@foreach\s*\(\s*var\s+\w+\s+in\s+[^)]+\)\s*\{"))
        {
            var match = Regex.Match(result, @"@foreach\s*\(\s*var\s+(\w+)\s+in\s+([^)]+)\)\s*\{");
            if (!match.Success) break;

            var itemVar = match.Groups[1].Value;
            var collection = TransformExpression(match.Groups[2].Value.Trim());
            var startIndex = match.Index + match.Length;
            var content = ExtractBalancedBraces(result, startIndex - 1);
            var endIndex = startIndex + content.Length + 1;

            // Transform loop variable references inside content
            var transformedContent = content.Trim();

            // Handle attribute bindings: Attr="@var.Prop" → Attr={var.Prop}
            transformedContent = Regex.Replace(transformedContent, $@"(\w+)=""@{itemVar}\.(\w+)""", $"$1={{{itemVar}.$2}}");
            // Handle attribute bindings: Attr="@var" → Attr={var}
            transformedContent = Regex.Replace(transformedContent, $@"(\w+)=""@{itemVar}""", $"$1={{{itemVar}}}");

            // Handle text content: @var.Prop → {var.Prop}
            transformedContent = Regex.Replace(transformedContent, $@"@{itemVar}\.(\w+)", $"{{{itemVar}.$1}}");
            // Handle text content: @var → {var}
            transformedContent = Regex.Replace(transformedContent, $@"@{itemVar}(?![\w\.])", $"{{{itemVar}}}");

            var replacement = $"{{{collection}.map(({itemVar}, index) => (\n{transformedContent}\n))}}";
            result = result.Substring(0, match.Index) + replacement + result.Substring(endIndex);
        }

        return result;
    }

    private string ExtractBalancedBraces(string source, int openBraceIndex)
    {
        var depth = 1;
        var i = openBraceIndex + 1;
        while (i < source.Length && depth > 0)
        {
            if (source[i] == '{') depth++;
            else if (source[i] == '}') depth--;
            i++;
        }
        return source.Substring(openBraceIndex + 1, i - openBraceIndex - 2);
    }

    private string TransformCondition(string condition)
    {
        var result = TransformExpression(condition);
        // Transform C# string methods to JS
        result = Regex.Replace(result, @"!string\.IsNullOrEmpty\(props\.(\w+)\)", "props.$1");
        result = Regex.Replace(result, @"string\.IsNullOrEmpty\(props\.(\w+)\)", "!props.$1");
        return result;
    }

    private string TransformExpression(string expr)
    {
        expr = expr.Trim();
        // Props.X → props.X
        expr = Regex.Replace(expr, @"Props\.", "props.");
        return expr;
    }

    private bool IsHtmlElement(string tagName)
    {
        // If first letter is uppercase, it's a React component (e.g., Button vs button)
        if (char.IsUpper(tagName[0]))
        {
            return false;
        }

        var htmlElements = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "div", "span", "p", "a", "button", "input", "form", "label",
            "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "li",
            "table", "tr", "td", "th", "thead", "tbody", "tfoot",
            "header", "footer", "section", "article", "nav", "aside",
            "main", "figure", "figcaption", "img", "video", "audio",
            "canvas", "svg", "path", "br", "hr", "strong", "em"
        };
        return htmlElements.Contains(tagName);
    }
}
