using System.Text;
using System.Text.RegularExpressions;

namespace Shalimar.Razor;

/// <summary>
/// TSX emitter that transforms Razor source into React TSX code.
///
/// Key transformations:
/// - class → className
/// - for → htmlFor
/// - @Props.X → {props.X}
/// - @if (cond) { } → {cond && ( )}
/// - @foreach (var x in xs) { } → {xs.map(x => ( ))}
/// - @onclick → onClick
/// </summary>
public class TsxEmitter
{
    private readonly string _fileName;
    private string _componentName;
    private string? _propsTypeName;
    private readonly HashSet<string> _childComponents = new();

    public TsxEmitter(string fileName)
    {
        _fileName = fileName;
        _componentName = Path.GetFileNameWithoutExtension(fileName);
    }

    public string Emit(string razorSource)
    {
        // Extract metadata
        ExtractMetadata(razorSource);

        var sb = new StringBuilder();

        // Header comment
        sb.AppendLine("// Generated by Shalimar.Razor - DO NOT EDIT");
        sb.AppendLine("import React from 'react';");

        // Child component imports
        foreach (var comp in _childComponents.OrderBy(c => c))
        {
            sb.AppendLine($"import {{ {comp} }} from './{comp}';");
        }

        sb.AppendLine();

        // Props interface
        if (_propsTypeName != null)
        {
            sb.AppendLine($"export interface {_propsTypeName} {{");
            var props = ExtractPropsUsage(razorSource);
            foreach (var prop in props)
            {
                sb.AppendLine($"  {prop}: any;");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Component function
        var propsParam = _propsTypeName != null ? $"props: {_propsTypeName}" : "";
        sb.AppendLine($"export function {_componentName}({propsParam}) {{");
        sb.AppendLine("  return (");

        // Transform the markup
        var jsx = TransformToJsx(razorSource);
        sb.Append(jsx);

        sb.AppendLine("  );");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void ExtractMetadata(string source)
    {
        // Extract props type from @inherits
        var inheritsMatch = Regex.Match(source, @"@inherits\s+SliceComponent<(\w+)>");
        if (inheritsMatch.Success)
        {
            _propsTypeName = inheritsMatch.Groups[1].Value;
        }

        // Find child components (PascalCase tags)
        var componentMatches = Regex.Matches(source, @"<([A-Z][a-zA-Z0-9]*)\s");
        foreach (Match match in componentMatches)
        {
            var name = match.Groups[1].Value;
            if (!IsHtmlElement(name))
            {
                _childComponents.Add(name);
            }
        }
    }

    private HashSet<string> ExtractPropsUsage(string source)
    {
        var props = new HashSet<string>();
        var matches = Regex.Matches(source, @"Props\.(\w+)");
        foreach (Match match in matches)
        {
            props.Add(match.Groups[1].Value);
        }
        return props;
    }

    private string TransformToJsx(string source)
    {
        var result = source;

        // Remove @inherits directive
        result = Regex.Replace(result, @"@inherits[^\n]+\n?", "");

        // Transform class → className
        result = Regex.Replace(result, @"class=""([^""]+)""", "className=\"$1\"");

        // Transform for → htmlFor
        result = Regex.Replace(result, @"\sfor=""([^""]+)""", " htmlFor=\"$1\"");

        // Transform @onclick → onClick
        result = Regex.Replace(result, @"@onclick=""@(\w+)""", "onClick={$1}");
        result = Regex.Replace(result, @"@onclick=""@\(\(\)\s*=>\s*([^)]+)\(\)\)""", "onClick={() => $1()}");

        // Transform @onchange → onChange
        result = Regex.Replace(result, @"@onchange=""@(\w+)""", "onChange={$1}");

        // Transform simple expressions @Props.X → {props.X}
        result = Regex.Replace(result, @"@Props\.(\w+)", "{props.$1}");

        // Transform attribute expressions prop="@value" → prop={value}
        result = Regex.Replace(result, @"=""@(\w+)""", "={$1}");

        // Transform @if blocks
        result = TransformIfBlocks(result);

        // Transform @foreach blocks
        result = TransformForeachBlocks(result);

        // Indent properly
        var lines = result.Trim().Split('\n');
        var sb = new StringBuilder();
        foreach (var line in lines)
        {
            var trimmed = line.Trim();
            if (!string.IsNullOrEmpty(trimmed))
            {
                sb.AppendLine("    " + trimmed);
            }
        }

        return sb.ToString();
    }

    private string TransformIfBlocks(string source)
    {
        var result = source;

        // Transform @if (condition) { content } → {condition && ( content )}
        result = Regex.Replace(result,
            @"@if\s*\(([^)]+)\)\s*\{([^}]+)\}",
            m =>
            {
                var condition = TransformCondition(m.Groups[1].Value);
                var content = m.Groups[2].Value.Trim();
                return $"{{({condition}) && (\n{content}\n)}}";
            },
            RegexOptions.Singleline);

        return result;
    }

    private string TransformForeachBlocks(string source)
    {
        var result = source;

        // Transform @foreach (var x in collection) { content } → {collection.map(x => ( content ))}
        result = Regex.Replace(result,
            @"@foreach\s*\(\s*var\s+(\w+)\s+in\s+([^)]+)\)\s*\{([^}]+)\}",
            m =>
            {
                var itemVar = m.Groups[1].Value;
                var collection = TransformExpression(m.Groups[2].Value.Trim());
                var content = m.Groups[3].Value.Trim();
                return $"{{{collection}.map(({itemVar}) => (\n{content}\n))}}";
            },
            RegexOptions.Singleline);

        return result;
    }

    private string TransformCondition(string condition)
    {
        return TransformExpression(condition);
    }

    private string TransformExpression(string expr)
    {
        expr = expr.Trim();
        // Props.X → props.X
        expr = Regex.Replace(expr, @"Props\.", "props.");
        return expr;
    }

    private bool IsHtmlElement(string tagName)
    {
        var htmlElements = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "div", "span", "p", "a", "button", "input", "form", "label",
            "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "li",
            "table", "tr", "td", "th", "thead", "tbody", "tfoot",
            "header", "footer", "section", "article", "nav", "aside",
            "main", "figure", "figcaption", "img", "video", "audio",
            "canvas", "svg", "path", "br", "hr", "strong", "em"
        };
        return htmlElements.Contains(tagName);
    }
}
