using Microsoft.AspNetCore.Razor.Language;
using Microsoft.AspNetCore.Razor.Language.Syntax;
using System.Text;
using System.Text.RegularExpressions;

namespace Shalimar.Razor;

/// <summary>
/// TSX emitter that walks the Razor syntax tree and generates React TSX code.
///
/// This is the core of Shalimar - we take Microsoft's parsed syntax tree
/// and emit valid TypeScript/React JSX.
///
/// Key transformations:
/// - MarkupElement → JSX tags
/// - MarkupAttribute → JSX attributes (class→className, for→htmlFor)
/// - CSharpExpression (@x) → {x}
/// - CSharpCodeBlock (@if/@foreach) → JSX control flow patterns
/// - @inherits SliceComponent<T> → component props typing
/// </summary>
public class TsxEmitter
{
    private readonly StringBuilder _output = new();
    private readonly string _fileName;
    private string? _propsTypeName;
    private string _componentName;
    private int _indentLevel = 0;
    private readonly List<string> _imports = new();
    private readonly HashSet<string> _childComponents = new();

    public TsxEmitter(string fileName)
    {
        _fileName = fileName;
        _componentName = Path.GetFileNameWithoutExtension(fileName);
    }

    public string Emit(RazorSyntaxTree syntaxTree)
    {
        // First pass: extract directives and metadata
        ExtractMetadata(syntaxTree.Root);

        // Build output
        var result = new StringBuilder();

        // Header comment
        result.AppendLine("// Generated by Shalimar.Razor - DO NOT EDIT");
        result.AppendLine("import React from 'react';");

        // Add child component imports
        foreach (var component in _childComponents.OrderBy(c => c))
        {
            result.AppendLine($"import {{ {component} }} from './{component}';");
        }

        result.AppendLine();

        // Props interface if we have one
        if (_propsTypeName != null)
        {
            result.AppendLine($"export interface {_propsTypeName} {{");
            result.AppendLine("  // TODO: Extract props from usage");
            result.AppendLine("}");
            result.AppendLine();
        }

        // Component function
        var propsParam = _propsTypeName != null ? $"props: {_propsTypeName}" : "";
        result.AppendLine($"export function {_componentName}({propsParam}) {{");
        result.AppendLine("  return (");

        // Second pass: emit JSX
        _indentLevel = 2;
        EmitNode(syntaxTree.Root, result);

        result.AppendLine("  );");
        result.AppendLine("}");

        return result.ToString();
    }

    private void ExtractMetadata(SyntaxNode root)
    {
        foreach (var node in root.DescendantNodes())
        {
            if (node is RazorDirectiveSyntax directive)
            {
                var directiveContent = directive.ToString();

                // Extract @inherits SliceComponent<PropsType>
                var inheritsMatch = Regex.Match(directiveContent, @"@inherits\s+SliceComponent<(\w+)>");
                if (inheritsMatch.Success)
                {
                    _propsTypeName = inheritsMatch.Groups[1].Value;
                }
            }

            // Detect child component usage (PascalCase tags)
            if (node is MarkupTagHelperElementSyntax tagHelper)
            {
                var tagName = tagHelper.StartTag?.Name?.ToString() ?? "";
                if (char.IsUpper(tagName.FirstOrDefault()) && !IsHtmlElement(tagName))
                {
                    _childComponents.Add(tagName);
                }
            }

            if (node is MarkupElementSyntax element)
            {
                var tagName = element.StartTag?.Name?.ToString() ?? "";
                if (char.IsUpper(tagName.FirstOrDefault()) && !IsHtmlElement(tagName))
                {
                    _childComponents.Add(tagName);
                }
            }
        }
    }

    private void EmitNode(SyntaxNode node, StringBuilder sb)
    {
        switch (node)
        {
            case RazorDocumentSyntax doc:
                EmitChildren(doc, sb);
                break;

            case MarkupBlockSyntax markupBlock:
                EmitChildren(markupBlock, sb);
                break;

            case MarkupElementSyntax element:
                EmitMarkupElement(element, sb);
                break;

            case MarkupTagHelperElementSyntax tagHelper:
                EmitTagHelperElement(tagHelper, sb);
                break;

            case MarkupTextLiteralSyntax textLiteral:
                EmitTextLiteral(textLiteral, sb);
                break;

            case CSharpExpressionLiteralSyntax csharpExpr:
                EmitCSharpExpression(csharpExpr, sb);
                break;

            case CSharpCodeBlockSyntax codeBlock:
                EmitCSharpCodeBlock(codeBlock, sb);
                break;

            case RazorDirectiveSyntax directive:
                // Directives are handled in metadata extraction
                break;

            case CSharpStatementLiteralSyntax statement:
                EmitCSharpStatement(statement, sb);
                break;

            default:
                // Recurse into children for unhandled node types
                EmitChildren(node, sb);
                break;
        }
    }

    private void EmitChildren(SyntaxNode node, StringBuilder sb)
    {
        foreach (var child in node.ChildNodes())
        {
            EmitNode(child, sb);
        }
    }

    private void EmitMarkupElement(MarkupElementSyntax element, StringBuilder sb)
    {
        var tagName = element.StartTag?.Name?.ToString() ?? "div";
        var jsxTagName = TransformTagName(tagName);

        // Check if this is a self-closing element
        var isSelfClosing = element.EndTag == null ||
                            string.IsNullOrEmpty(element.EndTag.Name?.ToString());

        // Start tag
        Indent(sb);
        sb.Append($"<{jsxTagName}");

        // Emit attributes
        if (element.StartTag != null)
        {
            EmitAttributes(element.StartTag, sb);
        }

        if (isSelfClosing && !element.Body.Any())
        {
            sb.AppendLine(" />");
        }
        else
        {
            sb.AppendLine(">");

            // Emit children
            _indentLevel++;
            foreach (var child in element.Body)
            {
                EmitNode(child, sb);
            }
            _indentLevel--;

            // End tag
            Indent(sb);
            sb.AppendLine($"</{jsxTagName}>");
        }
    }

    private void EmitTagHelperElement(MarkupTagHelperElementSyntax element, StringBuilder sb)
    {
        var tagName = element.StartTag?.Name?.ToString() ?? "div";
        var jsxTagName = TransformTagName(tagName);

        var isSelfClosing = element.EndTag == null ||
                            string.IsNullOrEmpty(element.EndTag.Name?.ToString());

        Indent(sb);
        sb.Append($"<{jsxTagName}");

        // Emit attributes
        if (element.StartTag != null)
        {
            EmitTagHelperAttributes(element.StartTag, sb);
        }

        if (isSelfClosing && !element.Body.Any())
        {
            sb.AppendLine(" />");
        }
        else
        {
            sb.AppendLine(">");

            _indentLevel++;
            foreach (var child in element.Body)
            {
                EmitNode(child, sb);
            }
            _indentLevel--;

            Indent(sb);
            sb.AppendLine($"</{jsxTagName}>");
        }
    }

    private void EmitAttributes(MarkupStartTagSyntax startTag, StringBuilder sb)
    {
        foreach (var attr in startTag.Attributes)
        {
            if (attr is MarkupAttributeBlockSyntax attrBlock)
            {
                var name = attrBlock.Name?.ToString() ?? "";
                var jsxName = AttributeTransformer.TransformName(name);

                // Get the value
                var valueNode = attrBlock.Value;
                var value = valueNode?.ToString()?.Trim('"', '\'') ?? "";

                // Check if value contains C# expression
                if (value.StartsWith("@"))
                {
                    var expr = TransformExpression(value.TrimStart('@'));
                    sb.Append($" {jsxName}={{{expr}}}");
                }
                else
                {
                    sb.Append($" {jsxName}=\"{value}\"");
                }
            }
            else if (attr is MarkupMinimizedAttributeBlockSyntax minimized)
            {
                var name = minimized.Name?.ToString() ?? "";
                var jsxName = AttributeTransformer.TransformName(name);
                sb.Append($" {jsxName}");
            }
        }
    }

    private void EmitTagHelperAttributes(MarkupTagHelperStartTagSyntax startTag, StringBuilder sb)
    {
        foreach (var attr in startTag.Attributes)
        {
            if (attr is MarkupTagHelperAttributeSyntax thAttr)
            {
                var name = thAttr.Name?.ToString() ?? "";
                var jsxName = AttributeTransformer.TransformName(name);

                var value = thAttr.Value?.ToString()?.Trim() ?? "";

                // Check for C# expression
                if (value.StartsWith("@"))
                {
                    var expr = TransformExpression(value.TrimStart('@'));
                    sb.Append($" {jsxName}={{{expr}}}");
                }
                else if (!string.IsNullOrEmpty(value))
                {
                    sb.Append($" {jsxName}=\"{value}\"");
                }
            }
            else if (attr is MarkupMinimizedTagHelperAttributeSyntax minimized)
            {
                var name = minimized.Name?.ToString() ?? "";
                var jsxName = AttributeTransformer.TransformName(name);
                sb.Append($" {jsxName}");
            }
        }
    }

    private void EmitTextLiteral(MarkupTextLiteralSyntax textLiteral, StringBuilder sb)
    {
        var content = textLiteral.Content?.ToString() ?? "";

        // Skip pure whitespace between elements
        if (string.IsNullOrWhiteSpace(content))
        {
            return;
        }

        // Trim and emit meaningful text
        content = content.Trim();
        if (!string.IsNullOrEmpty(content))
        {
            Indent(sb);
            sb.AppendLine(content);
        }
    }

    private void EmitCSharpExpression(CSharpExpressionLiteralSyntax expr, StringBuilder sb)
    {
        var content = expr.Content?.ToString() ?? "";
        content = content.Trim();

        if (!string.IsNullOrEmpty(content))
        {
            var transformed = TransformExpression(content);
            sb.Append($"{{{transformed}}}");
        }
    }

    private void EmitCSharpCodeBlock(CSharpCodeBlockSyntax codeBlock, StringBuilder sb)
    {
        var content = codeBlock.ToString().Trim();

        // Handle @if
        if (content.StartsWith("@if"))
        {
            EmitIfStatement(codeBlock, sb);
        }
        // Handle @foreach
        else if (content.StartsWith("@foreach"))
        {
            EmitForeachStatement(codeBlock, sb);
        }
        // Handle @code blocks (skip for now, they're for logic)
        else if (content.StartsWith("@code"))
        {
            // Skip @code blocks in JSX output
        }
        else
        {
            // For other code blocks, emit children
            EmitChildren(codeBlock, sb);
        }
    }

    private void EmitCSharpStatement(CSharpStatementLiteralSyntax statement, StringBuilder sb)
    {
        // Handle individual C# statements within code blocks
        // These are usually handled by parent code block nodes
    }

    private void EmitIfStatement(CSharpCodeBlockSyntax codeBlock, StringBuilder sb)
    {
        var content = codeBlock.ToString();

        // Extract condition
        var condMatch = Regex.Match(content, @"@if\s*\(([^)]+)\)");
        if (!condMatch.Success) return;

        var condition = TransformExpression(condMatch.Groups[1].Value);

        // Check for else clause
        var hasElse = content.Contains("else");

        if (hasElse)
        {
            // Extract both branches - simplified for POC
            var parts = Regex.Split(content, @"\}\s*else\s*\{");
            if (parts.Length >= 2)
            {
                Indent(sb);
                sb.AppendLine($"{{({condition}) ? (");
                _indentLevel++;

                // Emit "if" content
                EmitMarkupFromCodeBlock(parts[0], sb);

                _indentLevel--;
                Indent(sb);
                sb.AppendLine(") : (");
                _indentLevel++;

                // Emit "else" content
                EmitMarkupFromCodeBlock(parts[1], sb);

                _indentLevel--;
                Indent(sb);
                sb.AppendLine(")}}");
            }
        }
        else
        {
            Indent(sb);
            sb.AppendLine($"{{({condition}) && (");
            _indentLevel++;

            // Emit children (the content inside the if block)
            foreach (var child in codeBlock.DescendantNodes())
            {
                if (child is MarkupElementSyntax || child is MarkupBlockSyntax)
                {
                    EmitNode(child, sb);
                }
            }

            _indentLevel--;
            Indent(sb);
            sb.AppendLine(")}}");
        }
    }

    private void EmitForeachStatement(CSharpCodeBlockSyntax codeBlock, StringBuilder sb)
    {
        var content = codeBlock.ToString();

        // Extract loop variable and collection
        var foreachMatch = Regex.Match(content, @"@foreach\s*\(\s*var\s+(\w+)\s+in\s+([^)]+)\)");
        if (!foreachMatch.Success) return;

        var itemVar = foreachMatch.Groups[1].Value;
        var collection = TransformExpression(foreachMatch.Groups[2].Value.Trim());

        Indent(sb);
        sb.AppendLine($"{{{collection}.map(({itemVar}) => (");
        _indentLevel++;

        // Emit children (the content inside the foreach block)
        foreach (var child in codeBlock.DescendantNodes())
        {
            if (child is MarkupElementSyntax || child is MarkupTagHelperElementSyntax)
            {
                EmitNode(child, sb);
                break; // Usually only one root element in foreach
            }
        }

        _indentLevel--;
        Indent(sb);
        sb.AppendLine("))}}");
    }

    private void EmitMarkupFromCodeBlock(string codeContent, StringBuilder sb)
    {
        // Very simplified - just emit any HTML-like content found
        var tagMatch = Regex.Match(codeContent, @"<(\w+)[^>]*>.*?</\1>", RegexOptions.Singleline);
        if (tagMatch.Success)
        {
            Indent(sb);
            sb.AppendLine(tagMatch.Value);
        }
    }

    private string TransformExpression(string csharpExpr)
    {
        return ExpressionTransformer.Transform(csharpExpr);
    }

    private string TransformTagName(string tagName)
    {
        // Keep PascalCase component names as-is
        if (char.IsUpper(tagName.FirstOrDefault()))
        {
            return tagName;
        }
        return tagName;
    }

    private bool IsHtmlElement(string tagName)
    {
        var htmlElements = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "div", "span", "p", "a", "button", "input", "form", "label",
            "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "li",
            "table", "tr", "td", "th", "thead", "tbody", "tfoot",
            "header", "footer", "section", "article", "nav", "aside",
            "main", "figure", "figcaption", "img", "video", "audio",
            "canvas", "svg", "path", "circle", "rect", "text",
            "br", "hr", "strong", "em", "b", "i", "u", "s",
            "pre", "code", "blockquote", "q", "cite",
            "select", "option", "textarea", "fieldset", "legend"
        };
        return htmlElements.Contains(tagName);
    }

    private void Indent(StringBuilder sb)
    {
        sb.Append(new string(' ', _indentLevel * 2));
    }
}
