using System.Reflection;
using System.Text;
using System.Text.Json;
using Impulse.Core;

namespace Impulse.SourceGen;

/// <summary>
/// CLI tool that extracts TypeScript types, Zod schemas, and route definitions
/// from compiled Impulse assemblies.
///
/// Usage: impulse-gen [assembly-path] [output-dir]
/// </summary>
public static class ImpulseGenerator
{
    public static int Main(string[] args)
    {
        if (args.Length < 2)
        {
            Console.Error.WriteLine("Usage: impulse-gen <assembly-path> <output-dir>");
            return 1;
        }

        var assemblyPath = args[0];
        var outputDir = args[1];

        if (!File.Exists(assemblyPath))
        {
            Console.Error.WriteLine($"Assembly not found: {assemblyPath}");
            return 1;
        }

        try
        {
            Directory.CreateDirectory(outputDir);
            var assembly = Assembly.LoadFrom(assemblyPath);
            var endpoints = DiscoverEndpoints(assembly);

            if (endpoints.Count == 0)
            {
                Console.WriteLine("No Impulse endpoints found.");
                return 0;
            }

            Console.WriteLine($"Found {endpoints.Count} endpoint(s):");
            foreach (var ep in endpoints)
            {
                Console.WriteLine($"  - {ep.Name}: {ep.Route}");
            }

            // Generate outputs
            GenerateRoutes(endpoints, outputDir);
            GenerateTypeScript(endpoints, outputDir);
            GenerateZodSchemas(endpoints, outputDir);

            Console.WriteLine($"\nGenerated files in {outputDir}");
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
            return 1;
        }
    }

    private static List<EndpointInfo> DiscoverEndpoints(Assembly assembly)
    {
        var endpoints = new List<EndpointInfo>();

        foreach (var type in assembly.GetExportedTypes())
        {
            var attr = type.GetCustomAttribute<ImpulseEndpointAttribute>();
            if (attr is null) continue;

            // Find request/response types from base class
            var baseType = type.BaseType;
            Type? requestType = null;
            Type? responseType = null;

            while (baseType != null)
            {
                if (baseType.IsGenericType)
                {
                    var genericDef = baseType.GetGenericTypeDefinition();
                    if (genericDef.Name.StartsWith("ImpulseEndpoint"))
                    {
                        var args = baseType.GetGenericArguments();
                        if (args.Length == 2)
                        {
                            requestType = args[0];
                            responseType = args[1];
                        }
                        else if (args.Length == 1)
                        {
                            responseType = args[0];
                        }
                        break;
                    }
                }
                baseType = baseType.BaseType;
            }

            endpoints.Add(new EndpointInfo(
                Name: type.Name,
                FullName: type.FullName ?? type.Name,
                Route: attr.Route,
                RequestType: requestType,
                ResponseType: responseType));
        }

        return endpoints;
    }

    private static void GenerateRoutes(List<EndpointInfo> endpoints, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        sb.AppendLine("export const Routes = {");
        foreach (var ep in endpoints)
        {
            var key = ep.Name.Replace("Endpoint", "");
            sb.AppendLine($"  {key}: '{ep.Route}',");
        }
        sb.AppendLine("} as const;");

        File.WriteAllText(Path.Combine(outputDir, "routes.ts"), sb.ToString());
    }

    private static void GenerateTypeScript(List<EndpointInfo> endpoints, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        sb.AppendLine();

        foreach (var ep in endpoints)
        {
            if (ep.RequestType != null)
            {
                sb.AppendLine($"export interface {ep.RequestType.Name} {{");
                foreach (var prop in ep.RequestType.GetProperties())
                {
                    var tsType = GetTypeScriptType(prop.PropertyType);
                    var optional = IsNullable(prop.PropertyType) ? "?" : "";
                    sb.AppendLine($"  {ToCamelCase(prop.Name)}{optional}: {tsType};");
                }
                sb.AppendLine("}");
                sb.AppendLine();
            }

            if (ep.ResponseType != null)
            {
                sb.AppendLine($"export interface {ep.ResponseType.Name} {{");
                foreach (var prop in ep.ResponseType.GetProperties())
                {
                    var tsType = GetTypeScriptType(prop.PropertyType);
                    var optional = IsNullable(prop.PropertyType) ? "?" : "";
                    sb.AppendLine($"  {ToCamelCase(prop.Name)}{optional}: {tsType};");
                }
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        File.WriteAllText(Path.Combine(outputDir, "types.ts"), sb.ToString());
    }

    private static void GenerateZodSchemas(List<EndpointInfo> endpoints, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        sb.AppendLine("import { z } from 'zod';");
        sb.AppendLine();

        foreach (var ep in endpoints)
        {
            if (ep.RequestType != null)
            {
                sb.AppendLine($"export const {ep.RequestType.Name}Schema = z.object({{");
                foreach (var prop in ep.RequestType.GetProperties())
                {
                    var zodType = GetZodType(prop.PropertyType);
                    sb.AppendLine($"  {ToCamelCase(prop.Name)}: {zodType},");
                }
                sb.AppendLine("});");
                sb.AppendLine();
            }
        }

        File.WriteAllText(Path.Combine(outputDir, "validation.ts"), sb.ToString());
    }

    private static string GetTypeScriptType(Type type)
    {
        var underlying = Nullable.GetUnderlyingType(type) ?? type;

        if (underlying == typeof(string)) return "string";
        if (underlying == typeof(int) || underlying == typeof(long) ||
            underlying == typeof(float) || underlying == typeof(double) ||
            underlying == typeof(decimal)) return "number";
        if (underlying == typeof(bool)) return "boolean";
        if (underlying == typeof(DateTime) || underlying == typeof(DateTimeOffset)) return "string";
        if (underlying == typeof(Guid)) return "string";
        if (underlying.IsArray) return $"{GetTypeScriptType(underlying.GetElementType()!)}[]";
        if (underlying.IsGenericType && underlying.GetGenericTypeDefinition() == typeof(List<>))
            return $"{GetTypeScriptType(underlying.GetGenericArguments()[0])}[]";

        return underlying.Name;
    }

    private static string GetZodType(Type type)
    {
        var underlying = Nullable.GetUnderlyingType(type);
        var isNullable = underlying != null;
        var baseType = underlying ?? type;

        string zodBase;
        if (baseType == typeof(string)) zodBase = "z.string()";
        else if (baseType == typeof(int) || baseType == typeof(long)) zodBase = "z.number().int()";
        else if (baseType == typeof(float) || baseType == typeof(double) || baseType == typeof(decimal))
            zodBase = "z.number()";
        else if (baseType == typeof(bool)) zodBase = "z.boolean()";
        else if (baseType == typeof(DateTime) || baseType == typeof(DateTimeOffset))
            zodBase = "z.string().datetime()";
        else if (baseType == typeof(Guid)) zodBase = "z.string().uuid()";
        else if (baseType.IsArray)
            zodBase = $"z.array({GetZodType(baseType.GetElementType()!)})";
        else if (baseType.IsGenericType && baseType.GetGenericTypeDefinition() == typeof(List<>))
            zodBase = $"z.array({GetZodType(baseType.GetGenericArguments()[0])})";
        else zodBase = "z.unknown()";

        return isNullable ? $"{zodBase}.nullable()" : zodBase;
    }

    private static bool IsNullable(Type type)
    {
        return Nullable.GetUnderlyingType(type) != null ||
               !type.IsValueType;
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name[1..];
    }
}

internal record EndpointInfo(
    string Name,
    string FullName,
    string Route,
    Type? RequestType,
    Type? ResponseType);
