using System.Reflection;
using System.Text;
using System.Text.Json;
using Impulse.Core;

namespace Impulse.SourceGen;

/// <summary>
/// CLI tool that extracts TypeScript types, Zod schemas, and route definitions
/// from compiled Impulse assemblies.
///
/// Usage: impulse-gen [assembly-path] [output-dir]
/// </summary>
public static class ImpulseGenerator
{
    public static int Main(string[] args)
    {
        if (args.Length < 2)
        {
            Console.Error.WriteLine("Usage: impulse-gen <assembly-path> <output-dir>");
            return 1;
        }

        var assemblyPath = args[0];
        var outputDir = args[1];

        if (!File.Exists(assemblyPath))
        {
            Console.Error.WriteLine($"Assembly not found: {assemblyPath}");
            return 1;
        }

        try
        {
            Directory.CreateDirectory(outputDir);
            var assembly = Assembly.LoadFrom(assemblyPath);
            var endpoints = DiscoverEndpoints(assembly);

            if (endpoints.Count == 0)
            {
                Console.WriteLine("No Impulse endpoints found.");
                return 0;
            }

            Console.WriteLine($"Found {endpoints.Count} endpoint(s):");
            foreach (var ep in endpoints)
            {
                Console.WriteLine($"  - [{ep.Method}] {ep.Name}: {ep.Route}");
            }

            // Generate outputs
            GenerateRoutes(endpoints, outputDir);
            GenerateTypeScript(endpoints, outputDir);
            GenerateZodSchemas(endpoints, outputDir);

            Console.WriteLine($"\nGenerated files in {outputDir}");
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
            return 1;
        }
    }

    private static List<EndpointInfo> DiscoverEndpoints(Assembly assembly)
    {
        var endpoints = new List<EndpointInfo>();

        foreach (var type in assembly.GetExportedTypes())
        {
            var attr = type.GetCustomAttribute<ImpulseEndpointAttribute>();
            if (attr is null) continue;

            // Find request/response types from base class
            var baseType = type.BaseType;
            Type? requestType = null;
            Type? responseType = null;

            while (baseType != null)
            {
                if (baseType.IsGenericType)
                {
                    var genericDef = baseType.GetGenericTypeDefinition();
                    if (genericDef.Name.StartsWith("ImpulseEndpoint"))
                    {
                        var args = baseType.GetGenericArguments();
                        if (args.Length == 2)
                        {
                            requestType = args[0];
                            responseType = args[1];
                        }
                        else if (args.Length == 1)
                        {
                            responseType = args[0];
                        }
                        break;
                    }
                }
                baseType = baseType.BaseType;
            }

            endpoints.Add(new EndpointInfo(
                Name: type.Name,
                FullName: type.FullName ?? type.Name,
                Route: attr.Route,
                Method: attr.Method,
                RequestType: requestType,
                ResponseType: responseType));
        }

        return endpoints;
    }

    private static void GenerateRoutes(List<EndpointInfo> endpoints, string outputDir)
    {
        // Generate RoutePaths.ts - constants for use in links
        var pathsSb = new StringBuilder();
        pathsSb.AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        pathsSb.AppendLine();
        pathsSb.AppendLine("/**");
        pathsSb.AppendLine(" * Type-safe route path constants.");
        pathsSb.AppendLine(" * Use these for Link components and navigation.");
        pathsSb.AppendLine(" */");
        pathsSb.AppendLine("export const RoutePaths = {");
        foreach (var ep in endpoints)
        {
            var key = ep.Name.Replace("Endpoint", "");
            pathsSb.AppendLine($"  {key}: '{ep.Route}' as const,");
        }
        pathsSb.AppendLine("} as const;");
        pathsSb.AppendLine();
        pathsSb.AppendLine("export type RoutePath = typeof RoutePaths[keyof typeof RoutePaths];");
        File.WriteAllText(Path.Combine(outputDir, "routePaths.ts"), pathsSb.ToString());

        // Generate TanStack Router route files
        var routesDir = Path.Combine(outputDir, "routes");
        Directory.CreateDirectory(routesDir);

        foreach (var ep in endpoints)
        {
            GenerateTanStackRoute(ep, routesDir);
        }

        // Generate loaders.ts - typed loader functions
        GenerateLoaders(endpoints, outputDir);

        // Generate mutations.ts - typed mutation functions
        GenerateMutations(endpoints, outputDir);
    }

    private static void GenerateTanStackRoute(EndpointInfo endpoint, string routesDir)
    {
        var sb = new StringBuilder();
        var routeName = endpoint.Name.Replace("Endpoint", "");
        var fileName = RouteToFileName(endpoint.Route);
        var responseName = endpoint.ResponseType?.Name ?? "unknown";

        sb.AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        sb.AppendLine("import { createFileRoute } from '@tanstack/react-router';");
        sb.AppendLine("import type { ImpulseContext } from '@impulse/react';");

        if (endpoint.ResponseType != null)
            sb.AppendLine($"import type {{ {responseName} }} from '../types';");

        sb.AppendLine();
        sb.AppendLine($"export const Route = createFileRoute('{endpoint.Route}')({{");

        // Add loader for GET endpoints (no request body or simple request)
        if (endpoint.ResponseType != null)
        {
            sb.AppendLine("  loader: async ({ context, params }) => {");
            sb.AppendLine("    const { impulse } = context as ImpulseContext;");
            sb.AppendLine($"    return impulse<{responseName}>('{endpoint.Route}'");

            // Add params interpolation if route has parameters
            if (endpoint.Route.Contains('{'))
            {
                sb.AppendLine("      .replace(/{(\\w+)}/g, (_, key) => params[key])");
            }
            sb.AppendLine("    );");
            sb.AppendLine("  },");
        }

        sb.AppendLine("});");

        var filePath = Path.Combine(routesDir, fileName);
        var dir = Path.GetDirectoryName(filePath);
        if (dir != null) Directory.CreateDirectory(dir);
        File.WriteAllText(filePath, sb.ToString());
    }

    private static void GenerateLoaders(List<EndpointInfo> endpoints, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        sb.AppendLine("import type { ImpulseContext } from '@impulse/react';");
        sb.AppendLine("import * as Types from './types';");
        sb.AppendLine();
        sb.AppendLine("/**");
        sb.AppendLine(" * Type-safe loader functions for GET endpoints.");
        sb.AppendLine(" * Use these in your route loaders.");
        sb.AppendLine(" */");
        sb.AppendLine("export const Loaders = {");

        // Only generate loaders for GET endpoints
        foreach (var ep in endpoints.Where(e => e.IsQuery && e.ResponseType != null))
        {
            var name = ep.Name.Replace("Endpoint", "");
            var responseName = ep.ResponseType!.Name;
            var hasParams = ep.Route.Contains('{');

            sb.AppendLine($"  /** GET {ep.Route} */");
            if (hasParams)
            {
                var paramNames = ExtractRouteParams(ep.Route);
                var paramsType = string.Join(", ", paramNames.Select(p => $"{p}: string"));
                sb.AppendLine($"  {name}: async (ctx: ImpulseContext, params: {{ {paramsType} }}): Promise<Types.{responseName}> => {{");
                sb.AppendLine($"    let url = '{ep.Route}';");
                foreach (var param in paramNames)
                {
                    sb.AppendLine($"    url = url.replace('{{{param}}}', params.{param});");
                }
                sb.AppendLine("    return ctx.impulse<Types." + responseName + ">(url);");
            }
            else
            {
                sb.AppendLine($"  {name}: async (ctx: ImpulseContext): Promise<Types.{responseName}> => {{");
                sb.AppendLine($"    return ctx.impulse<Types.{responseName}>('{ep.Route}');");
            }
            sb.AppendLine("  },");
            sb.AppendLine();
        }

        sb.AppendLine("} as const;");
        File.WriteAllText(Path.Combine(outputDir, "loaders.ts"), sb.ToString());
    }

    private static void GenerateMutations(List<EndpointInfo> endpoints, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        sb.AppendLine("import { useMutation } from '@tanstack/react-query';");
        sb.AppendLine("import { useRouter } from '@tanstack/react-router';");
        sb.AppendLine("import type { ImpulseContext } from '@impulse/react';");
        sb.AppendLine("import * as Types from './types';");
        sb.AppendLine("import * as Schemas from './validation';");
        sb.AppendLine();

        // Only generate mutations for POST/PUT/PATCH/DELETE endpoints
        foreach (var ep in endpoints.Where(e => e.IsMutation && e.RequestType != null))
        {
            var name = ep.Name.Replace("Endpoint", "");
            var requestName = ep.RequestType!.Name;
            var responseName = ep.ResponseType?.Name ?? "void";
            var schemaName = $"{requestName}Schema";
            var httpMethod = ep.Method.ToString().ToUpperInvariant();

            sb.AppendLine($"/**");
            sb.AppendLine($" * Mutation hook for {name}");
            sb.AppendLine($" * {httpMethod} {ep.Route}");
            sb.AppendLine($" */");
            sb.AppendLine($"export function use{name}Mutation(ctx: ImpulseContext) {{");
            sb.AppendLine("  const router = useRouter();");
            sb.AppendLine();
            sb.AppendLine($"  return useMutation({{");
            sb.AppendLine($"    mutationFn: async (data: Types.{requestName}) => {{");
            sb.AppendLine($"      // Validate with Zod before sending");
            sb.AppendLine($"      const validated = Schemas.{schemaName}.parse(data);");
            sb.AppendLine($"      return ctx.impulseMutate<Types.{requestName}, Types.{responseName}>(");
            sb.AppendLine($"        '{ep.Route}',");
            sb.AppendLine($"        validated,");
            sb.AppendLine($"        '{httpMethod}'");
            sb.AppendLine($"      );");
            sb.AppendLine($"    }},");
            sb.AppendLine($"    onSuccess: async () => {{");
            sb.AppendLine($"      // Invalidate and refetch related queries");
            sb.AppendLine($"      await router.invalidate();");
            sb.AppendLine($"    }},");
            sb.AppendLine($"  }});");
            sb.AppendLine($"}}");
            sb.AppendLine();
        }

        File.WriteAllText(Path.Combine(outputDir, "mutations.ts"), sb.ToString());
    }

    private static string RouteToFileName(string route)
    {
        // Convert /residents/{id} to residents.$id.tsx
        var fileName = route
            .TrimStart('/')
            .Replace("{", "$")
            .Replace("}", "")
            .Replace("/", ".");

        return fileName + ".tsx";
    }

    private static List<string> ExtractRouteParams(string route)
    {
        var matches = System.Text.RegularExpressions.Regex.Matches(route, @"\{(\w+)\}");
        return matches.Select(m => m.Groups[1].Value).ToList();
    }

    private static void GenerateTypeScript(List<EndpointInfo> endpoints, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        sb.AppendLine();

        foreach (var ep in endpoints)
        {
            if (ep.RequestType != null)
            {
                sb.AppendLine($"export interface {ep.RequestType.Name} {{");
                foreach (var prop in ep.RequestType.GetProperties())
                {
                    var tsType = GetTypeScriptType(prop.PropertyType);
                    var optional = IsNullable(prop.PropertyType) ? "?" : "";
                    sb.AppendLine($"  {ToCamelCase(prop.Name)}{optional}: {tsType};");
                }
                sb.AppendLine("}");
                sb.AppendLine();
            }

            if (ep.ResponseType != null)
            {
                sb.AppendLine($"export interface {ep.ResponseType.Name} {{");
                foreach (var prop in ep.ResponseType.GetProperties())
                {
                    var tsType = GetTypeScriptType(prop.PropertyType);
                    var optional = IsNullable(prop.PropertyType) ? "?" : "";
                    sb.AppendLine($"  {ToCamelCase(prop.Name)}{optional}: {tsType};");
                }
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        File.WriteAllText(Path.Combine(outputDir, "types.ts"), sb.ToString());
    }

    private static void GenerateZodSchemas(List<EndpointInfo> endpoints, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        sb.AppendLine("import { z } from 'zod';");
        sb.AppendLine();

        foreach (var ep in endpoints)
        {
            if (ep.RequestType != null)
            {
                sb.AppendLine($"export const {ep.RequestType.Name}Schema = z.object({{");
                foreach (var prop in ep.RequestType.GetProperties())
                {
                    var zodType = GetZodType(prop.PropertyType);
                    sb.AppendLine($"  {ToCamelCase(prop.Name)}: {zodType},");
                }
                sb.AppendLine("});");
                sb.AppendLine();
            }
        }

        File.WriteAllText(Path.Combine(outputDir, "validation.ts"), sb.ToString());
    }

    private static string GetTypeScriptType(Type type)
    {
        var underlying = Nullable.GetUnderlyingType(type) ?? type;

        if (underlying == typeof(string)) return "string";
        if (underlying == typeof(int) || underlying == typeof(long) ||
            underlying == typeof(float) || underlying == typeof(double) ||
            underlying == typeof(decimal)) return "number";
        if (underlying == typeof(bool)) return "boolean";
        if (underlying == typeof(DateTime) || underlying == typeof(DateTimeOffset)) return "string";
        if (underlying == typeof(Guid)) return "string";
        if (underlying.IsArray) return $"{GetTypeScriptType(underlying.GetElementType()!)}[]";
        if (underlying.IsGenericType)
        {
            var genericDef = underlying.GetGenericTypeDefinition();
            if (genericDef == typeof(List<>))
                return $"{GetTypeScriptType(underlying.GetGenericArguments()[0])}[]";
            if (genericDef == typeof(Dictionary<,>))
            {
                var keyType = GetTypeScriptType(underlying.GetGenericArguments()[0]);
                var valueType = GetTypeScriptType(underlying.GetGenericArguments()[1]);
                return $"Record<{keyType}, {valueType}>";
            }
        }
        if (underlying.IsEnum)
            return underlying.Name;

        return underlying.Name;
    }

    private static string GetZodType(Type type)
    {
        var underlying = Nullable.GetUnderlyingType(type);
        var isNullable = underlying != null;
        var baseType = underlying ?? type;

        string zodBase;
        if (baseType == typeof(string)) zodBase = "z.string()";
        else if (baseType == typeof(int) || baseType == typeof(long)) zodBase = "z.number().int()";
        else if (baseType == typeof(float) || baseType == typeof(double) || baseType == typeof(decimal))
            zodBase = "z.number()";
        else if (baseType == typeof(bool)) zodBase = "z.boolean()";
        else if (baseType == typeof(DateTime) || baseType == typeof(DateTimeOffset))
            zodBase = "z.string().datetime()";
        else if (baseType == typeof(Guid)) zodBase = "z.string().uuid()";
        else if (baseType.IsArray)
            zodBase = $"z.array({GetZodType(baseType.GetElementType()!)})";
        else if (baseType.IsGenericType)
        {
            var genericDef = baseType.GetGenericTypeDefinition();
            if (genericDef == typeof(List<>))
                zodBase = $"z.array({GetZodType(baseType.GetGenericArguments()[0])})";
            else if (genericDef == typeof(Dictionary<,>))
                zodBase = $"z.record({GetZodType(baseType.GetGenericArguments()[0])}, {GetZodType(baseType.GetGenericArguments()[1])})";
            else
                zodBase = "z.unknown()";
        }
        else if (baseType.IsEnum)
            zodBase = $"z.nativeEnum({baseType.Name})";
        else zodBase = "z.unknown()";

        return isNullable ? $"{zodBase}.nullable()" : zodBase;
    }

    private static bool IsNullable(Type type)
    {
        return Nullable.GetUnderlyingType(type) != null ||
               !type.IsValueType;
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name[1..];
    }
}

internal record EndpointInfo(
    string Name,
    string FullName,
    string Route,
    ImpulseMethod Method,
    Type? RequestType,
    Type? ResponseType)
{
    public bool IsQuery => Method == ImpulseMethod.Get;
    public bool IsMutation => Method is ImpulseMethod.Post or ImpulseMethod.Put or ImpulseMethod.Patch or ImpulseMethod.Delete;
}
