/**
 * Generated by Moj TanStack DSL
 * Complex nested state store example
 */
import { Store } from '@tanstack/store';

// ============= Complex Nested Type Definitions =============

export interface Address {
  street: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
  coordinates: {
    lat: number;
    lng: number;
  };
}

export interface ContactInfo {
  email: string;
  phone: string;
  alternatePhone?: string;
  addresses: {
    home: Address;
    work?: Address;
    shipping?: Address;
  };
}

export interface NotificationSettings {
  email: {
    marketing: boolean;
    transactional: boolean;
    newsletter: boolean;
    frequency: 'instant' | 'daily' | 'weekly';
  };
  push: {
    enabled: boolean;
    sound: boolean;
    vibrate: boolean;
    categories: {
      orders: boolean;
      promotions: boolean;
      reminders: boolean;
      social: boolean;
    };
  };
  sms: {
    enabled: boolean;
    phoneVerified: boolean;
  };
}

export interface UserPreferences {
  theme: 'light' | 'dark' | 'system';
  language: string;
  timezone: string;
  currency: string;
  dateFormat: string;
  notifications: NotificationSettings;
  accessibility: {
    reduceMotion: boolean;
    highContrast: boolean;
    fontSize: 'small' | 'medium' | 'large' | 'xlarge';
  };
  privacy: {
    shareAnalytics: boolean;
    showOnlineStatus: boolean;
    allowSearchEngineIndexing: boolean;
  };
}

export interface CartItem {
  productId: string;
  name: string;
  quantity: number;
  price: number;
  variant?: {
    id: string;
    name: string;
    attributes: Record<string, string>;
  };
  customizations?: Array<{
    type: string;
    value: string;
    price: number;
  }>;
}

export interface Cart {
  items: CartItem[];
  subtotal: number;
  tax: number;
  shipping: number;
  discount: {
    code?: string;
    amount: number;
    type: 'percentage' | 'fixed';
  };
  total: number;
  lastUpdated: string;
}

export interface User {
  id: string;
  username: string;
  displayName: string;
  avatar?: string;
  role: 'user' | 'admin' | 'moderator';
  contact: ContactInfo;
  preferences: UserPreferences;
  metadata: {
    createdAt: string;
    lastLoginAt: string;
    loginCount: number;
    verifiedEmail: boolean;
    verifiedPhone: boolean;
  };
}

export interface AppState {
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
  cart: Cart;
  recentlyViewed: Array<{
    productId: string;
    name: string;
    viewedAt: string;
    category: string;
  }>;
  ui: {
    sidebarOpen: boolean;
    modalStack: Array<{
      id: string;
      type: string;
      props: Record<string, unknown>;
    }>;
    toasts: Array<{
      id: string;
      type: 'success' | 'error' | 'warning' | 'info';
      message: string;
      duration: number;
    }>;
    breadcrumbs: Array<{
      label: string;
      path: string;
    }>;
  };
  filters: {
    products: {
      categories: string[];
      priceRange: { min: number; max: number };
      brands: string[];
      ratings: number[];
      inStock: boolean;
      sortBy: 'price-asc' | 'price-desc' | 'name' | 'rating' | 'newest';
    };
  };
}

// ============= Initial State with Complex Nesting =============

const initialState: AppState = {
  user: null,
  isAuthenticated: false,
  isLoading: false,
  cart: {
    items: [],
    subtotal: 0,
    tax: 0,
    shipping: 0,
    discount: {
      code: undefined,
      amount: 0,
      type: 'fixed'
    },
    total: 0,
    lastUpdated: new Date().toISOString()
  },
  recentlyViewed: [],
  ui: {
    sidebarOpen: false,
    modalStack: [],
    toasts: [],
    breadcrumbs: []
  },
  filters: {
    products: {
      categories: [],
      priceRange: { min: 0, max: 10000 },
      brands: [],
      ratings: [],
      inStock: false,
      sortBy: 'newest'
    }
  }
};

// ============= Store Instance =============

export const appStore = new Store<AppState>(initialState);

// ============= Selectors (Complex Derived State) =============

export const selectCartItemCount = (state: AppState): number => {
  return state.cart.items.reduce((sum, item) => sum + item.quantity, 0);
};

export const selectCartTotalWithDiscounts = (state: AppState): number => {
  const { subtotal, tax, shipping, discount } = state.cart;
  const discountAmount = discount.type === 'percentage'
    ? subtotal * (discount.amount / 100)
    : discount.amount;
  return subtotal + tax + shipping - discountAmount;
};

export const selectUserFullAddress = (state: AppState): string | null => {
  if (!state.user?.contact.addresses.home) return null;
  const addr = state.user.contact.addresses.home;
  return `${addr.street}, ${addr.city}, ${addr.state} ${addr.zipCode}, ${addr.country}`;
};

export const selectActiveFiltersCount = (state: AppState): number => {
  const { categories, brands, ratings, inStock } = state.filters.products;
  return categories.length + brands.length + ratings.length + (inStock ? 1 : 0);
};

export const selectNotificationPreferences = (state: AppState): NotificationSettings | null => {
  return state.user?.preferences.notifications ?? null;
};

// ============= Actions =============

export const setUser = (user: User) => {
  appStore.setState((state) => ({
    ...state,
    user,
    isAuthenticated: true,
    isLoading: false
  }));
};

export const logout = () => {
  appStore.setState((state) => ({
    ...state,
    user: null,
    isAuthenticated: false,
    cart: initialState.cart
  }));
};

export const updateUserPreferences = (preferences: Partial<UserPreferences>) => {
  appStore.setState((state) => {
    if (!state.user) return state;
    return {
      ...state,
      user: {
        ...state.user,
        preferences: {
          ...state.user.preferences,
          ...preferences
        }
      }
    };
  });
};

export const updateNotificationSettings = (
  category: keyof NotificationSettings,
  settings: Partial<NotificationSettings[typeof category]>
) => {
  appStore.setState((state) => {
    if (!state.user) return state;
    return {
      ...state,
      user: {
        ...state.user,
        preferences: {
          ...state.user.preferences,
          notifications: {
            ...state.user.preferences.notifications,
            [category]: {
              ...state.user.preferences.notifications[category],
              ...settings
            }
          }
        }
      }
    };
  });
};

export const addToCart = (item: CartItem) => {
  appStore.setState((state) => {
    const existingIndex = state.cart.items.findIndex(
      (i) => i.productId === item.productId &&
             JSON.stringify(i.variant) === JSON.stringify(item.variant)
    );

    let newItems: CartItem[];
    if (existingIndex >= 0) {
      newItems = state.cart.items.map((i, idx) =>
        idx === existingIndex
          ? { ...i, quantity: i.quantity + item.quantity }
          : i
      );
    } else {
      newItems = [...state.cart.items, item];
    }

    const subtotal = newItems.reduce((sum, i) => sum + i.price * i.quantity, 0);
    const tax = subtotal * 0.08; // 8% tax

    return {
      ...state,
      cart: {
        ...state.cart,
        items: newItems,
        subtotal,
        tax,
        total: subtotal + tax + state.cart.shipping - state.cart.discount.amount,
        lastUpdated: new Date().toISOString()
      }
    };
  });
};

export const removeFromCart = (productId: string, variantId?: string) => {
  appStore.setState((state) => {
    const newItems = state.cart.items.filter(
      (i) => !(i.productId === productId && i.variant?.id === variantId)
    );
    const subtotal = newItems.reduce((sum, i) => sum + i.price * i.quantity, 0);
    const tax = subtotal * 0.08;

    return {
      ...state,
      cart: {
        ...state.cart,
        items: newItems,
        subtotal,
        tax,
        total: subtotal + tax + state.cart.shipping - state.cart.discount.amount,
        lastUpdated: new Date().toISOString()
      }
    };
  });
};

export const applyDiscountCode = (code: string, amount: number, type: 'percentage' | 'fixed') => {
  appStore.setState((state) => {
    const discountAmount = type === 'percentage'
      ? state.cart.subtotal * (amount / 100)
      : amount;

    return {
      ...state,
      cart: {
        ...state.cart,
        discount: { code, amount, type },
        total: state.cart.subtotal + state.cart.tax + state.cart.shipping - discountAmount,
        lastUpdated: new Date().toISOString()
      }
    };
  });
};

export const updateAddress = (
  type: 'home' | 'work' | 'shipping',
  address: Address
) => {
  appStore.setState((state) => {
    if (!state.user) return state;
    return {
      ...state,
      user: {
        ...state.user,
        contact: {
          ...state.user.contact,
          addresses: {
            ...state.user.contact.addresses,
            [type]: address
          }
        }
      }
    };
  });
};

export const showToast = (
  type: 'success' | 'error' | 'warning' | 'info',
  message: string,
  duration: number = 3000
) => {
  const id = `toast-${Date.now()}`;
  appStore.setState((state) => ({
    ...state,
    ui: {
      ...state.ui,
      toasts: [...state.ui.toasts, { id, type, message, duration }]
    }
  }));

  // Auto-remove after duration
  setTimeout(() => {
    appStore.setState((state) => ({
      ...state,
      ui: {
        ...state.ui,
        toasts: state.ui.toasts.filter((t) => t.id !== id)
      }
    }));
  }, duration);
};

export const openModal = (type: string, props: Record<string, unknown> = {}) => {
  const id = `modal-${Date.now()}`;
  appStore.setState((state) => ({
    ...state,
    ui: {
      ...state.ui,
      modalStack: [...state.ui.modalStack, { id, type, props }]
    }
  }));
  return id;
};

export const closeModal = (id?: string) => {
  appStore.setState((state) => ({
    ...state,
    ui: {
      ...state.ui,
      modalStack: id
        ? state.ui.modalStack.filter((m) => m.id !== id)
        : state.ui.modalStack.slice(0, -1)
    }
  }));
};

export const setProductFilters = (
  filters: Partial<AppState['filters']['products']>
) => {
  appStore.setState((state) => ({
    ...state,
    filters: {
      ...state.filters,
      products: {
        ...state.filters.products,
        ...filters
      }
    }
  }));
};

export const addRecentlyViewed = (product: {
  productId: string;
  name: string;
  category: string;
}) => {
  appStore.setState((state) => {
    const filtered = state.recentlyViewed.filter(
      (p) => p.productId !== product.productId
    );
    return {
      ...state,
      recentlyViewed: [
        { ...product, viewedAt: new Date().toISOString() },
        ...filtered
      ].slice(0, 20) // Keep last 20
    };
  });
};

// ============= Store Subscription Helper =============

export const subscribeToStore = <T>(
  selector: (state: AppState) => T,
  callback: (value: T) => void
) => {
  let previousValue = selector(appStore.state);
  callback(previousValue);

  return appStore.subscribe(() => {
    const newValue = selector(appStore.state);
    if (newValue !== previousValue) {
      previousValue = newValue;
      callback(newValue);
    }
  });
};
