using Xunit;

namespace Shalimar.Razor.Tests;

public class EmitterTests
{
    private readonly RazorReactCompiler _compiler = new();

    [Fact]
    public void TransformsClassToClassName()
    {
        var razor = """<div class="test"></div>""";
        var tsx = _compiler.CompileToString(razor);
        Assert.Contains("className=\"test\"", tsx);
    }

    [Fact]
    public void TransformsForToHtmlFor()
    {
        var razor = """<label for="input-id">Label</label>""";
        var tsx = _compiler.CompileToString(razor);
        Assert.Contains("htmlFor=\"input-id\"", tsx);
    }

    [Fact]
    public void TransformsPropsExpression()
    {
        var razor = """<span>@Props.Name</span>""";
        var tsx = _compiler.CompileToString(razor);
        Assert.Contains("{props.Name}", tsx);
    }

    [Fact]
    public void TransformsOnClickEvent()
    {
        var razor = """<button @onclick="@HandleClick">Click</button>""";
        var tsx = _compiler.CompileToString(razor);
        Assert.Contains("onClick={HandleClick}", tsx);
    }

    [Fact]
    public void PreservesPascalCaseComponents()
    {
        var razor = """<MyComponent prop="value" />""";
        var tsx = _compiler.CompileToString(razor);
        Assert.Contains("<MyComponent", tsx);
    }

    [Fact]
    public void HandlesNestedElements()
    {
        var razor = """
            <div class="outer">
                <span class="inner">Content</span>
            </div>
            """;
        var tsx = _compiler.CompileToString(razor);
        Assert.Contains("className=\"outer\"", tsx);
        Assert.Contains("className=\"inner\"", tsx);
    }

    [Fact]
    public void ExtractsPropsTypeFromInherits()
    {
        var razor = """
            @inherits SliceComponent<MyComponentProps>
            <div>Content</div>
            """;
        var tsx = _compiler.CompileToString(razor);
        Assert.Contains("interface MyComponentProps", tsx);
        Assert.Contains("props: MyComponentProps", tsx);
    }

    [Fact]
    public void GeneratesReactImport()
    {
        var razor = """<div>Hello</div>""";
        var tsx = _compiler.CompileToString(razor);
        Assert.Contains("import React from 'react'", tsx);
    }

    [Fact]
    public void GeneratesFunctionComponent()
    {
        var razor = """<div>Hello</div>""";
        var tsx = _compiler.CompileToString(razor, "MyComponent.razor");
        Assert.Contains("export function MyComponent", tsx);
    }

    [Fact]
    public void AddsDoNotEditComment()
    {
        var razor = """<div>Hello</div>""";
        var tsx = _compiler.CompileToString(razor);
        Assert.Contains("Generated by Shalimar.Razor - DO NOT EDIT", tsx);
    }
}

public class ExpressionTransformerTests
{
    [Theory]
    [InlineData("Props.Name", "props.Name")]
    [InlineData("Props.Items.Count", "props.Items.length")]
    [InlineData("list.Select(x => x.Name)", "list.map(x => x.Name)")]
    [InlineData("list.Where(x => x.Active)", "list.filter(x => x.Active)")]
    [InlineData("list.Any()", "list.length > 0")]
    [InlineData("list.First()", "list[0]")]
    [InlineData("str.ToUpper()", "str.toUpperCase()")]
    [InlineData("str.ToLower()", "str.toLowerCase()")]
    [InlineData("str.StartsWith(\"a\")", "str.startsWith(\"a\")")]
    [InlineData("string.IsNullOrEmpty(s)", "!s")]
    public void TransformsExpressions(string csharp, string expectedJs)
    {
        var result = ExpressionTransformer.Transform(csharp);
        Assert.Equal(expectedJs, result);
    }
}

public class AttributeTransformerTests
{
    [Theory]
    [InlineData("class", "className")]
    [InlineData("for", "htmlFor")]
    [InlineData("@onclick", "onClick")]
    [InlineData("@onchange", "onChange")]
    [InlineData("tabindex", "tabIndex")]
    [InlineData("readonly", "readOnly")]
    [InlineData("data-testid", "data-testid")]
    [InlineData("aria-label", "aria-label")]
    public void TransformsAttributeNames(string html, string expectedJsx)
    {
        var result = AttributeTransformer.TransformName(html);
        Assert.Equal(expectedJsx, result);
    }
}
