using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Impulse.SourceGen;

/// <summary>
/// Source generator that produces TypeScript interfaces from C# Props records.
/// Outputs TypeScript as commented C# code for MSBuild extraction.
/// </summary>
[Generator]
public class ImpulseTypeScriptGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all record declarations ending with "Props"
        var propsRecords = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsPropsRecord(node),
                transform: static (ctx, _) => GetPropsInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        // Collect all props and generate TypeScript
        var collected = propsRecords.Collect();

        context.RegisterSourceOutput(collected, static (ctx, records) =>
        {
            if (records.IsEmpty) return;

            var source = GenerateTypeScriptSource(records);
            ctx.AddSource("ImpulseTypes.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static bool IsPropsRecord(SyntaxNode node)
    {
        return node is RecordDeclarationSyntax record &&
               record.Identifier.Text.EndsWith("Props", StringComparison.Ordinal);
    }

    private static PropsInfo? GetPropsInfo(GeneratorSyntaxContext context)
    {
        var record = (RecordDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(record);

        if (symbol is null) return null;

        var properties = new List<PropertyInfo>();

        // Get properties from primary constructor parameters
        if (record.ParameterList is not null)
        {
            foreach (var param in record.ParameterList.Parameters)
            {
                var paramSymbol = context.SemanticModel.GetDeclaredSymbol(param);
                if (paramSymbol is IParameterSymbol ps)
                {
                    properties.Add(new PropertyInfo(
                        ps.Name,
                        GetTypeScriptType(ps.Type),
                        IsNullable(ps.Type)));
                }
            }
        }

        return new PropsInfo(
            symbol.Name,
            symbol.ContainingNamespace.ToDisplayString(),
            properties);
    }

    private static string GenerateTypeScriptSource(ImmutableArray<PropsInfo> records)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// This file contains generated TypeScript as comments.");
        sb.AppendLine("// MSBuild extracts this to .ts files during build.");
        sb.AppendLine();
        sb.AppendLine("namespace Impulse.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated TypeScript interfaces.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class ImpulseTypes");
        sb.AppendLine("{");
        sb.AppendLine("    // <impulse-typescript file=\"types.g.ts\">");
        sb.AppendLine("    // // This file is auto-generated by Impulse.SourceGen");
        sb.AppendLine("    // // Do not edit manually");
        sb.AppendLine("    //");

        foreach (var record in records.OrderBy(r => r.Name))
        {
            sb.AppendLine($"    // export interface {record.Name} {{");

            foreach (var prop in record.Properties)
            {
                var optionalMarker = prop.IsNullable ? "?" : "";
                var propName = ToCamelCase(prop.Name);
                sb.AppendLine($"    //   {propName}{optionalMarker}: {prop.TypeScriptType};");
            }

            sb.AppendLine("    // }");
            sb.AppendLine("    //");
        }

        sb.AppendLine("    // </impulse-typescript>");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetTypeScriptType(ITypeSymbol type)
    {
        // Handle nullable
        if (type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
        {
            return GetTypeScriptType(named.TypeArguments[0]) + " | null";
        }

        // Primitives
        return type.SpecialType switch
        {
            SpecialType.System_Int16 or
            SpecialType.System_Int32 or
            SpecialType.System_Int64 or
            SpecialType.System_Byte or
            SpecialType.System_Double or
            SpecialType.System_Single or
            SpecialType.System_Decimal => "number",

            SpecialType.System_String => "string",
            SpecialType.System_Boolean => "boolean",
            SpecialType.System_DateTime => "string",

            _ => GetComplexTypeScriptType(type)
        };
    }

    private static string GetComplexTypeScriptType(ITypeSymbol type)
    {
        var name = type.Name;

        // Handle common types
        if (name is "Guid" or "DateOnly" or "TimeOnly" or "DateTimeOffset")
        {
            return "string";
        }

        // Handle arrays
        if (type is IArrayTypeSymbol arrayType)
        {
            return $"readonly {GetTypeScriptType(arrayType.ElementType)}[]";
        }

        // Handle generic collections
        if (type is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var genericName = namedType.ConstructedFrom.Name;

            // List, IReadOnlyList, IEnumerable -> array
            if (genericName is "List" or "IList" or "IReadOnlyList" or "IEnumerable" or "ICollection" or "IReadOnlyCollection")
            {
                return $"readonly {GetTypeScriptType(namedType.TypeArguments[0])}[]";
            }

            // Dictionary -> Record
            if (genericName is "Dictionary" or "IDictionary" or "IReadOnlyDictionary")
            {
                return $"Record<{GetTypeScriptType(namedType.TypeArguments[0])}, {GetTypeScriptType(namedType.TypeArguments[1])}>";
            }
        }

        // Enum
        if (type.TypeKind == TypeKind.Enum)
        {
            return name;
        }

        // Other types - use the type name
        return name;
    }

    private static bool IsNullable(ITypeSymbol type)
    {
        if (type.NullableAnnotation == NullableAnnotation.Annotated)
            return true;

        if (type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            return true;

        return false;
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}

internal record PropsInfo(string Name, string Namespace, List<PropertyInfo> Properties);
internal record PropertyInfo(string Name, string TypeScriptType, bool IsNullable);
