// Generated by Shalimar.Razor - DO NOT EDIT
import React from 'react';
import { UserProfile } from './UserProfile';

export interface AppProps {
  Title: any;
  Description: any;
  Users: any;
}

export function App(props: AppProps) {
  return (
    <div className="app-container">
    <header className="app-header">
    <h1>{props.Title}</h1>
    <p>{props.Description}</p>
    </header>
    <main className="app-main">
    {props.Users.map((user, index) => (
    <UserProfile
    Name={user.Name}
    JobTitle={user.JobTitle}
    AvatarUrl={user.AvatarUrl}
    Initials={user.Initials}
    IsVerified={user.IsVerified}
    Bio={user.Bio}
    Stats={user.Stats}
    Skills={user.Skills}
    OnFollow={user.OnFollow}
    OnMessage={user.OnMessage}
    />
    ))}
    </main>
    <footer className="app-footer">
    <p>Generated from Razor by Shalimar Compiler</p>
    </footer>
    </div>
  );
}
