// Generated by Shalimar.Razor - DO NOT EDIT
import React from 'react';

export interface AvatarProps {
  ImageUrl: any;
  Alt: any;
  Initials: any;
}

export function Avatar(props: AvatarProps) {
  return (
    <div className="avatar">
    {(props.ImageUrl) && (
    <img src={props.ImageUrl} alt={props.Alt} className="avatar-image" />
    )}
    {(!props.ImageUrl) && (
    <span className="avatar-fallback">{props.Initials}</span>
    )}
    </div>
  );
}
