// Generated by Shalimar.Razor - DO NOT EDIT
import React from 'react';

export interface BadgeProps {
  Variant: any;
  Text: any;
}

export function Badge(props: BadgeProps) {
  return (
    <span className={`badge ${props.Variant}`}>
    {props.Text}
    </span>
  );
}
