// Generated by Shalimar.Razor - DO NOT EDIT
import React from 'react';

export interface ButtonProps {
  Variant: any;
  OnClick: any;
  Disabled: any;
  Children: any;
}

export function Button(props: ButtonProps) {
  return (
    <button
    className={`btn btn-${props.Variant}`}
    onClick={props.OnClick}
    disabled={props.Disabled}
    >
    {props.Children}
    </button>
  );
}
