// Generated by Shalimar.Razor - DO NOT EDIT
import React from 'react';

export interface CardProps {
  Title: any;
  Subtitle: any;
  Children: any;
  HasFooter: any;
  Footer: any;
}

export function Card(props: CardProps) {
  return (
    <div className="card">
    {(props.Title) && (
    <div className="card-header">
    <h3 className="card-title">{props.Title}</h3>
    {(props.Subtitle) && (
    <p className="card-subtitle">{props.Subtitle}</p>
    )}
    </div>
    )}
    <div className="card-body">
    {props.Children}
    </div>
    {(props.HasFooter) && (
    <div className="card-footer">
    {props.Footer}
    </div>
    )}
    </div>
  );
}
