// Generated by Shalimar.Razor - DO NOT EDIT
import React from 'react';
import { SkillTag } from './SkillTag';

export interface SkillsListProps {
  Title: any;
  Skills: any;
}

export function SkillsList(props: SkillsListProps) {
  return (
    <div className="skills-list">
    <h4 className="skills-title">{props.Title}</h4>
    <div className="skills-container">
    {props.Skills.map((skill, index) => (
    <SkillTag Name={skill} />
    ))}
    </div>
    </div>
  );
}
