// Generated by Shalimar.Razor - DO NOT EDIT
import React from 'react';

export interface SkillTagProps {
  Name: any;
}

export function SkillTag(props: SkillTagProps) {
  return (
    <span className="skill-tag">{props.Name}</span>
  );
}
