// Generated by Shalimar.Razor - DO NOT EDIT
import React from 'react';
import { StatItem } from './StatItem';

export interface StatsRowProps {
  Stats: any;
}

export function StatsRow(props: StatsRowProps) {
  return (
    <div className="stats-row">
    {props.Stats.map((stat, index) => (
    <StatItem Value={stat.Value} Label={stat.Label} />
    ))}
    </div>
  );
}
