// Generated by Shalimar.Razor - DO NOT EDIT
import React from 'react';

export interface StatItemProps {
  Value: any;
  Label: any;
}

export function StatItem(props: StatItemProps) {
  return (
    <div className="stat-item">
    <span className="stat-value">{props.Value}</span>
    <span className="stat-label">{props.Label}</span>
    </div>
  );
}
