// Generated by Shalimar.Razor - DO NOT EDIT
import React from 'react';
import { Avatar } from './Avatar';
import { Badge } from './Badge';
import { Button } from './Button';
import { Card } from './Card';
import { SkillsList } from './SkillsList';
import { StatsRow } from './StatsRow';

export interface UserProfileProps {
  Name: any;
  JobTitle: any;
  AvatarUrl: any;
  Initials: any;
  IsVerified: any;
  Stats: any;
  Bio: any;
  Skills: any;
  OnFollow: any;
  OnMessage: any;
}

export function UserProfile(props: UserProfileProps) {
  return (
    <Card Title={props.Name} Subtitle={props.JobTitle}>
    <div className="profile-content">
    <div className="profile-header">
    <Avatar ImageUrl={props.AvatarUrl} Initials={props.Initials} Alt={props.Name} />
    {(props.IsVerified) && (
    <Badge Text="Verified" Variant="success" />
    )}
    </div>
    <StatsRow Stats={props.Stats} />
    <div className="profile-bio">
    <p>{props.Bio}</p>
    </div>
    <SkillsList Title="Skills" Skills={props.Skills} />
    <div className="profile-actions">
    <Button Variant="primary" OnClick={props.OnFollow}>
    Follow
    </Button>
    <Button Variant="secondary" OnClick={props.OnMessage}>
    Message
    </Button>
    </div>
    </div>
    </Card>
  );
}
