using Moj.TanStack.Ast.Core;
using Moj.TanStack.Ast.CodeGen;

namespace Moj.TanStack.Dsl.Core;

/// <summary>
/// Builder for complete TypeScript files
/// </summary>
public sealed class TsFileBuilder
{
    private readonly List<TsNode> _nodes = [];
    private readonly string _fileName;

    public TsFileBuilder(string fileName)
    {
        _fileName = fileName;
    }

    /// <summary>
    /// Add an import declaration
    /// </summary>
    public TsFileBuilder Import(TsImportDeclaration import)
    {
        _nodes.Add(import);
        return this;
    }

    /// <summary>
    /// Add an import using builder
    /// </summary>
    public TsFileBuilder Import(TsImportBuilder import)
    {
        _nodes.Add(import.Build());
        return this;
    }

    /// <summary>
    /// Add a variable declaration
    /// </summary>
    public TsFileBuilder Variable(TsVariableDeclaration variable)
    {
        _nodes.Add(variable);
        return this;
    }

    /// <summary>
    /// Add an interface declaration
    /// </summary>
    public TsFileBuilder Interface(TsInterfaceDeclaration @interface)
    {
        _nodes.Add(@interface);
        return this;
    }

    /// <summary>
    /// Add a type alias declaration
    /// </summary>
    public TsFileBuilder TypeAlias(TsTypeAliasDeclaration typeAlias)
    {
        _nodes.Add(typeAlias);
        return this;
    }

    /// <summary>
    /// Add a function declaration
    /// </summary>
    public TsFileBuilder Function(TsFunctionDeclaration function)
    {
        _nodes.Add(function);
        return this;
    }

    /// <summary>
    /// Add an export declaration
    /// </summary>
    public TsFileBuilder Export(TsExportDeclaration export)
    {
        _nodes.Add(export);
        return this;
    }

    /// <summary>
    /// Add any node
    /// </summary>
    public TsFileBuilder Add(TsNode node)
    {
        _nodes.Add(node);
        return this;
    }

    /// <summary>
    /// Add multiple nodes
    /// </summary>
    public TsFileBuilder AddRange(IEnumerable<TsNode> nodes)
    {
        _nodes.AddRange(nodes);
        return this;
    }

    /// <summary>
    /// Add a comment
    /// </summary>
    public TsFileBuilder Comment(string text, bool multiLine = false)
    {
        _nodes.Add(new TsComment(text, multiLine));
        return this;
    }

    /// <summary>
    /// Build the AST program
    /// </summary>
    public TsProgram Build() => new(_nodes);

    /// <summary>
    /// Build and emit as TypeScript code
    /// </summary>
    public string Emit()
    {
        var program = Build();
        var emitter = new TypeScriptEmitter();
        return emitter.Emit(program);
    }

    /// <summary>
    /// Get the file name
    /// </summary>
    public string FileName => _fileName;
}

/// <summary>
/// Static factory for creating TypeScript files
/// </summary>
public static class TsFile
{
    /// <summary>
    /// Create a new TypeScript file
    /// </summary>
    public static TsFileBuilder Create(string fileName) => new(fileName);
}

/// <summary>
/// Represents a generated TypeScript output
/// </summary>
public sealed class TsGeneratedFile
{
    public required string FileName { get; init; }
    public required string Content { get; init; }
    public TsProgram? Ast { get; init; }

    /// <summary>
    /// Wrap TypeScript content in a C# comment block for source generator output
    /// </summary>
    public string ToCSharpEmbedded()
    {
        return $"""
            // <auto-generated>
            // This code was generated by Moj.TanStack.SourceGenerator
            // Do not modify this file directly.
            // </auto-generated>

            /* TS
            {Content}
            */
            """;
    }
}
