// This file is auto-generated by Impulse.CodeGen
// Do not edit manually

import type { ComponentType } from 'react';

// Dashboard
import { Dashboard } from '../Dashboard/Component';

// DynamicForms
import { DynamicForm, InsuranceApplicationForm } from '../DynamicForms/Component';

// Modal
import { ModalContainer, DeleteConfirmation, EditResidentModal } from '../Modal/Component';

// Pane
import { PaneContainer, ResidentDetailPane, ActivityFeedPane, FilterPane } from '../Pane/Component';

// Residents
import { ResidentsList } from '../Residents/List';
import { ResidentDetail, Medications } from '../Residents/Detail';

// Wizard
import { Wizard } from '../Wizard/Component';

/**
 * Auto-generated component registry.
 * Maps server-derived component paths to React components.
 * Paths are derived from Props type names using ComponentPathConvention.
 */
export const IMPULSE_COMPONENTS = new Map<string, ComponentType<unknown>>([
  // Dashboard: DashboardProps → ./Dashboard
  ['./Dashboard', Dashboard as ComponentType<unknown>],

  // DynamicForms: DynamicFormProps → ./DynamicForms (singular "DynamicForm" matches folder)
  ['./DynamicForms', DynamicForm as ComponentType<unknown>],
  // InsuranceApplicationProps → ./DynamicForms/InsuranceApplication
  ['./DynamicForms/InsuranceApplication', InsuranceApplicationForm as ComponentType<unknown>],

  // Modal: ModalContainerProps → ./Modal/Container
  ['./Modal/Container', ModalContainer as ComponentType<unknown>],
  // DeleteConfirmationProps → ./Modal/DeleteConfirmation
  ['./Modal/DeleteConfirmation', DeleteConfirmation as ComponentType<unknown>],
  // EditResidentModalProps → ./Modal/EditResidentModal
  ['./Modal/EditResidentModal', EditResidentModal as ComponentType<unknown>],

  // Pane: PaneContainerProps → ./Pane/Container
  ['./Pane/Container', PaneContainer as ComponentType<unknown>],
  // ResidentDetailPaneProps → ./Pane/ResidentDetailPane
  ['./Pane/ResidentDetailPane', ResidentDetailPane as ComponentType<unknown>],
  // ActivityFeedPaneProps → ./Pane/ActivityFeedPane
  ['./Pane/ActivityFeedPane', ActivityFeedPane as ComponentType<unknown>],
  // FilterPaneProps → ./Pane/FilterPane
  ['./Pane/FilterPane', FilterPane as ComponentType<unknown>],

  // Residents: ResidentsListProps → ./Residents/List
  ['./Residents/List', ResidentsList as ComponentType<unknown>],
  // ResidentDetailProps → ./Residents/Detail
  ['./Residents/Detail', ResidentDetail as ComponentType<unknown>],
  // MedicationsProps → ./Residents/Medications
  ['./Residents/Medications', Medications as ComponentType<unknown>],

  // Wizard: WizardProps → ./Wizard
  ['./Wizard', Wizard as ComponentType<unknown>],
]);

/**
 * Gets a component by its convention-derived path.
 */
export function getComponent(path: string): ComponentType<unknown> | undefined {
  return IMPULSE_COMPONENTS.get(path);
}
