// This file is auto-generated by Impulse.Validation
// Do not edit manually

import { z } from 'zod';

// ============================================================================
// FormSubmitRequest Schema
// ============================================================================

export const formSubmitRequestSchema = z.object({
  formId: z.string().min(1),
  values: z.object({
    stringValues: z.record(z.string(), z.string()),
    numberValues: z.record(z.string(), z.number()),
    booleanValues: z.record(z.string(), z.boolean()),
    multiSelectValues: z.record(z.string(), z.array(z.string())),
    dateValues: z.record(z.string(), z.string()),
  }),
});

export type FormSubmitRequest = z.infer<typeof formSubmitRequestSchema>;

// ============================================================================
// InsuranceFormData Schema
// ============================================================================

export const insuranceFormDataSchema = z.object({
  // Personal Information - always required
  firstName: z.string().min(1).max(50),
  lastName: z.string().min(1).max(50),
  dateOfBirth: z.string().nullable(),
  email: z.string().min(1).email(),
  phone: z.string().min(1),

  // Employment
  employmentStatus: z.string().min(1),
  employer: z.string().optional(),
  annualSalary: z.number().gt(0).nullable().optional(),

  // Insurance type
  insuranceType: z.string().min(1),

  // Auto insurance fields (conditional)
  vehicleMake: z.string().optional(),
  vehicleModel: z.string().optional(),
  vehicleYear: z.number().gte(1900).lte(2030).nullable().optional(),
  vinNumber: z.string().length(17).optional(),

  // Home insurance fields (conditional)
  propertyAddress: z.string().optional(),
  propertyValue: z.number().gt(50000).nullable().optional(),
  yearBuilt: z.number().gte(1800).lte(2030).nullable().optional(),
  constructionType: z.string().optional(),

  // Life insurance fields (conditional)
  coverageAmount: z.number().gt(10000).nullable().optional(),
  beneficiary: z.string().optional(),
  isSmoker: z.boolean().nullable().optional(),
  preExistingConditions: z.array(z.string()).optional(),

  // Payment
  paymentFrequency: z.string().min(1),
  paymentMethod: z.string().min(1),

  // Bank transfer fields (conditional)
  bankName: z.string().optional(),
  accountNumber: z.string().regex(/^\d+$/).optional(),
  routingNumber: z.string().length(9).optional(),

  // Credit card fields (conditional)
  cardNumber: z.string().optional(),
  cardExpiry: z.string().regex(/^\d{2}\/\d{2}$/).optional(),
  cardCvv: z.string().regex(/^\d{3,4}$/).optional(),
});

export type InsuranceFormData = z.infer<typeof insuranceFormDataSchema>;

// ============================================================================
// WizardFormData Schema
// ============================================================================

export const wizardFormDataSchema = z.object({
  firstName: z.string().min(1).max(50).optional(),
  lastName: z.string().min(1).max(50).optional(),
  dateOfBirth: z.string().nullable().optional(),
  gender: z.string().optional(),
  primaryPhysician: z.string().optional(),
  allergies: z.array(z.string()).optional(),
  medications: z.array(z.string()).optional(),
  bloodType: z.string().optional(),
  hasInsurance: z.boolean(),
  insuranceProvider: z.string().optional(),
  insurancePolicyNumber: z.string().optional(),
  emergencyContactName: z.string().optional(),
  emergencyContactPhone: z.string().optional(),
  emergencyContactRelation: z.string().optional(),
  buildingId: z.number().nullable().optional(),
  floorNumber: z.number().nullable().optional(),
  roomNumber: z.number().nullable().optional(),
});

export type WizardFormData = z.infer<typeof wizardFormDataSchema>;

// ============================================================================
// Validation Helper Functions
// ============================================================================

/**
 * Validates form data and returns validation errors in the same format as server.
 */
export function validateFormData<T>(
  schema: z.ZodType<T>,
  data: unknown
): { success: true; data: T } | { success: false; errors: Record<string, string[]> } {
  const result = schema.safeParse(data);

  if (result.success) {
    return { success: true, data: result.data };
  }

  const errors: Record<string, string[]> = {};
  for (const issue of result.error.issues) {
    const path = issue.path.join('.');
    if (!errors[path]) {
      errors[path] = [];
    }
    errors[path].push(issue.message);
  }

  return { success: false, errors };
}

/**
 * Creates a conditional schema that only validates when condition is met.
 */
export function when<T extends z.ZodTypeAny>(
  condition: boolean,
  schema: T
): T | z.ZodOptional<T> {
  return condition ? schema : schema.optional() as any;
}
