using System.Text;

namespace Impulse.CodeGen;

/// <summary>
/// Generates context.g.ts with app context type and permission constants.
/// </summary>
public sealed class ContextGenerator
{
    private readonly TypeScriptGenerator _typeGenerator;

    public ContextGenerator(TypeScriptGenerator? typeGenerator = null)
    {
        _typeGenerator = typeGenerator ?? new TypeScriptGenerator();
    }

    /// <summary>
    /// Generates the context.g.ts file content.
    /// </summary>
    public string Generate(Type contextType, Dictionary<string, Dictionary<string, string>>? permissions = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// This file is auto-generated by Impulse.CodeGen");
        sb.AppendLine("// Do not edit manually");
        sb.AppendLine();

        // Generate context interface
        sb.AppendLine(_typeGenerator.Generate([contextType]));

        // Generate permission constants if provided
        if (permissions is not null && permissions.Count > 0)
        {
            sb.AppendLine("export const Permissions = {");
            foreach (var (category, perms) in permissions)
            {
                sb.AppendLine($"  {category}: {{");
                foreach (var (name, value) in perms)
                {
                    sb.AppendLine($"    {name}: '{value}',");
                }
                sb.AppendLine("  },");
            }
            sb.AppendLine("} as const;");
            sb.AppendLine();
        }

        // Generate hasPermission helper
        sb.AppendLine("""
            export function hasPermission(perms: readonly string[], p: string): boolean {
              return perms.includes(p);
            }
            """);

        return sb.ToString();
    }
}
