using System.Reflection;
using Impulse.Core;
using Impulse.Validation;

namespace Impulse.CodeGen;

/// <summary>
/// Runs the code generation pipeline.
/// </summary>
public sealed class ImpulseCodeGenRunner
{
    private readonly ImpulseCodeGenOptions _options;
    private readonly TypeScriptGenerator _typeGenerator;
    private readonly ContextGenerator _contextGenerator;
    private readonly RoutesGenerator _routesGenerator;
    private readonly RegistryGenerator _registryGenerator;
    private readonly TanStackRouterGenerator _tanStackRouterGenerator;
    private readonly ValidationCodeGenerator _validationGenerator;

    public ImpulseCodeGenRunner(ImpulseCodeGenOptions options)
    {
        _options = options;
        _typeGenerator = new TypeScriptGenerator();
        _contextGenerator = new ContextGenerator(_typeGenerator);
        _routesGenerator = new RoutesGenerator();
        _registryGenerator = new RegistryGenerator();
        _tanStackRouterGenerator = new TanStackRouterGenerator();
        _validationGenerator = new ValidationCodeGenerator();
    }

    /// <summary>
    /// Runs the full code generation pipeline.
    /// </summary>
    public async Task RunAsync(ImpulseTypeRegistry registry, Type contextType, Assembly? validatorsAssembly = null)
    {
        Directory.CreateDirectory(_options.OutputDirectory);

        // Generate types.g.ts
        var allTypes = registry.AllTypes.ToList();
        var typesContent = _typeGenerator.Generate(allTypes);
        await WriteFileAsync("types.g.ts", typesContent);

        // Generate context.g.ts
        var contextContent = _contextGenerator.Generate(contextType, _options.Permissions);
        await WriteFileAsync("context.g.ts", contextContent);

        // Generate routes.g.ts
        var routesContent = _routesGenerator.Generate(registry);
        await WriteFileAsync("routes.g.ts", routesContent);

        // Generate registry.g.ts
        var registryContent = _registryGenerator.Generate(registry);
        await WriteFileAsync("registry.g.ts", registryContent);

        // Generate tanstack-router.g.ts (TanStack Router from Minimal API)
        var tanStackContent = _tanStackRouterGenerator.Generate(registry, _options.Version ?? "1.0.0");
        await WriteFileAsync("tanstack-router.g.ts", tanStackContent);

        // Generate validation.g.ts (Zod schemas from FluentValidation)
        if (validatorsAssembly is not null)
        {
            var validationContent = _validationGenerator.Generate(validatorsAssembly);
            await WriteFileAsync("validation.g.ts", validationContent);
        }

        // Generate index.ts barrel export
        var indexContent = GenerateIndex(validatorsAssembly is not null);
        await WriteFileAsync("index.ts", indexContent);

        Console.WriteLine($"Generated Impulse types in {_options.OutputDirectory}");
    }

    /// <summary>
    /// Discovers types from an assembly using Impulse attributes.
    /// </summary>
    public static IEnumerable<Type> DiscoverTypes(Assembly assembly)
    {
        return assembly.GetTypes()
            .Where(t => t.GetCustomAttribute<ImpulsePropsAttribute>() is not null ||
                        t.GetCustomAttribute<ImpulseRequestAttribute>() is not null ||
                        t.GetCustomAttribute<ImpulseResponseAttribute>() is not null);
    }

    private async Task WriteFileAsync(string fileName, string content)
    {
        var path = Path.Combine(_options.OutputDirectory, fileName);
        await File.WriteAllTextAsync(path, content);
        Console.WriteLine($"  Generated: {fileName}");
    }

    private static string GenerateIndex(bool includeValidation)
    {
        var validationExport = includeValidation ? "\nexport * from './validation.g';" : "";
        return """
            // This file is auto-generated by Impulse.CodeGen
            // Do not edit manually

            export * from './types.g';
            export * from './context.g';
            export * from './routes.g';
            export * from './registry.g';
            export { router, Routes } from './tanstack-router.g';
            """ + validationExport;
    }
}

/// <summary>
/// Options for code generation.
/// </summary>
public sealed class ImpulseCodeGenOptions
{
    public required string OutputDirectory { get; init; }
    public string? Version { get; init; }
    public Dictionary<string, Dictionary<string, string>>? Permissions { get; init; }
}

/// <summary>
/// Marks a type as props for code generation.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
public sealed class ImpulsePropsAttribute : Attribute { }

/// <summary>
/// Marks a type as a request for code generation.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
public sealed class ImpulseRequestAttribute : Attribute { }

/// <summary>
/// Marks a type as a response for code generation.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
public sealed class ImpulseResponseAttribute : Attribute { }
