<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Impulse.CodeGen</RootNamespace>
    <LangVersion>14.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Impulse.Core\Impulse.Core.csproj" />
    <ProjectReference Include="..\Impulse.Validation\Impulse.Validation.csproj" />
  </ItemGroup>

</Project>
