using System.Text;
using Impulse.Core;

namespace Impulse.CodeGen;

/// <summary>
/// Generates registry.g.ts with component path to React component mappings.
/// Uses convention-based paths derived from Props types.
/// </summary>
public sealed class RegistryGenerator
{
    /// <summary>
    /// Generates the registry.g.ts file content.
    /// Components follow naming convention:
    /// - Path "./Feature" → Import from "../Feature/Component"
    /// - Path "./Feature/Name" → Import from "../Feature/Name" or "../Feature/Component"
    /// </summary>
    public string Generate(ImpulseTypeRegistry registry)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// This file is auto-generated by Impulse.CodeGen");
        sb.AppendLine("// Do not edit manually");
        sb.AppendLine();
        sb.AppendLine("import type { ComponentType } from 'react';");
        sb.AppendLine();

        var componentPaths = GetComponentPaths(registry).ToList();

        // Group by feature folder for organized imports
        var grouped = componentPaths
            .GroupBy(p => GetFeatureFolder(p.Path))
            .OrderBy(g => g.Key);

        // Generate imports
        foreach (var group in grouped)
        {
            sb.AppendLine($"// {group.Key}");
            foreach (var component in group.OrderBy(c => c.Path))
            {
                var importPath = GetImportPath(component.Path);
                var componentName = GetComponentName(component.Path, component.PropsTypeName);
                sb.AppendLine($"import {{ {componentName} }} from '{importPath}';");
            }
            sb.AppendLine();
        }

        // Generate the registry map
        sb.AppendLine("/**");
        sb.AppendLine(" * Auto-generated component registry.");
        sb.AppendLine(" * Maps server-derived component paths to React components.");
        sb.AppendLine(" */");
        sb.AppendLine("export const IMPULSE_COMPONENTS = new Map<string, ComponentType<unknown>>([");

        foreach (var component in componentPaths.OrderBy(c => c.Path))
        {
            var componentName = GetComponentName(component.Path, component.PropsTypeName);
            sb.AppendLine($"  ['{component.Path}', {componentName} as ComponentType<unknown>],");
        }

        sb.AppendLine("]);");
        sb.AppendLine();

        // Export helper function
        sb.AppendLine("/**");
        sb.AppendLine(" * Gets a component by its convention-derived path.");
        sb.AppendLine(" */");
        sb.AppendLine("export function getComponent(path: string): ComponentType<unknown> | undefined {");
        sb.AppendLine("  return IMPULSE_COMPONENTS.get(path);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private IEnumerable<(string Path, string PropsTypeName)> GetComponentPaths(ImpulseTypeRegistry registry)
    {
        var seen = new HashSet<string>();

        foreach (var propsType in registry.PropsTypes)
        {
            var path = ComponentPathConvention.GetPath(propsType);
            if (seen.Add(path))
            {
                yield return (path, propsType.Name);
            }
        }
    }

    private static string GetFeatureFolder(string path)
    {
        // "./Dashboard" → "Dashboard"
        // "./Residents/List" → "Residents"
        var withoutPrefix = path.TrimStart('.', '/');
        var slashIndex = withoutPrefix.IndexOf('/');
        return slashIndex >= 0 ? withoutPrefix[..slashIndex] : withoutPrefix;
    }

    private static string GetImportPath(string componentPath)
    {
        // "./Dashboard" → "../Dashboard/Component"
        // "./Residents/List" → "../Residents/List"
        // "./Modal/Container" → "../Modal/Component"

        var withoutPrefix = componentPath.TrimStart('.', '/');
        var parts = withoutPrefix.Split('/');

        if (parts.Length == 1)
        {
            // Single part like "Dashboard" → "../Dashboard/Component"
            return $"../{parts[0]}/Component";
        }

        // Multi-part like "Residents/List" or "Modal/Container"
        var lastPart = parts[^1];

        // If the last part is "Container", use "Component" file
        if (lastPart == "Container")
        {
            return $"../{string.Join("/", parts[..^1])}/Component";
        }

        // Otherwise use the full path
        return $"../{withoutPrefix}";
    }

    private static string GetComponentName(string componentPath, string propsTypeName)
    {
        // Derive component export name from the Props type name
        // DashboardProps → Dashboard
        // ResidentsListProps → ResidentsList
        // ModalContainerProps → ModalContainer

        if (propsTypeName.EndsWith("Props"))
        {
            return propsTypeName[..^5];
        }

        return propsTypeName;
    }
}
