using System.Text;
using System.Text.RegularExpressions;
using Impulse.Core;

namespace Impulse.CodeGen;

/// <summary>
/// Generates routes.g.ts with typed route paths.
/// </summary>
public sealed partial class RoutesGenerator
{
    /// <summary>
    /// Generates the routes.g.ts file content.
    /// </summary>
    public string Generate(ImpulseTypeRegistry registry)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// This file is auto-generated by Impulse.CodeGen");
        sb.AppendLine("// Do not edit manually");
        sb.AppendLine();
        sb.AppendLine("export const Routes = {");

        var routes = registry.Components.Keys
            .OrderBy(r => r)
            .GroupBy(r => GetRoutePrefix(r))
            .ToList();

        foreach (var group in routes)
        {
            if (string.IsNullOrEmpty(group.Key))
            {
                // Root routes
                foreach (var route in group)
                {
                    var funcName = GetRouteFunctionName(route);
                    var (signature, body) = GenerateRouteFunction(route);
                    sb.AppendLine($"  {funcName}: {signature} => {body},");
                }
            }
            else
            {
                // Grouped routes
                sb.AppendLine($"  {ToCamelCase(group.Key)}: {{");
                foreach (var route in group)
                {
                    var funcName = GetRouteFunctionName(route, stripPrefix: group.Key);
                    var (signature, body) = GenerateRouteFunction(route);
                    sb.AppendLine($"    {funcName}: {signature} => {body},");
                }
                sb.AppendLine("  },");
            }
        }

        sb.AppendLine("} as const;");
        return sb.ToString();
    }

    private static string GetRoutePrefix(string route)
    {
        var parts = route.Trim('/').Split('/');
        if (parts.Length <= 1)
        {
            return string.Empty;
        }

        var firstPart = parts[0];
        return ParamPattern().IsMatch(firstPart) ? string.Empty : firstPart;
    }

    private static string GetRouteFunctionName(string route, string? stripPrefix = null)
    {
        var cleanRoute = route.Trim('/');
        if (!string.IsNullOrEmpty(stripPrefix))
        {
            cleanRoute = cleanRoute[(stripPrefix.Length + 1)..];
        }

        var parts = cleanRoute.Split('/')
            .Where(p => !ParamPattern().IsMatch(p))
            .ToList();

        if (parts.Count == 0)
        {
            return "list";
        }

        var lastName = parts.Last();
        return string.IsNullOrEmpty(lastName) ? "index" : ToCamelCase(lastName);
    }

    private static (string signature, string body) GenerateRouteFunction(string route)
    {
        var matches = ParamPattern().Matches(route);

        if (matches.Count == 0)
        {
            return ("()", $"'{route}' as const");
        }

        var parameters = new List<string>();
        var template = route;

        foreach (Match match in matches)
        {
            var paramName = match.Groups[1].Value;
            var paramType = match.Groups[2].Success ? GetTypeScriptTypeForConstraint(match.Groups[2].Value) : "string";
            parameters.Add($"{ToCamelCase(paramName)}: {paramType}");

            // Replace in template
            template = template.Replace(match.Value, $"${{{ToCamelCase(paramName)}}}");
        }

        return ($"({string.Join(", ", parameters)})", $"`{template}` as const");
    }

    private static string GetTypeScriptTypeForConstraint(string constraint)
    {
        return constraint switch
        {
            "int" or "long" => "number",
            "guid" => "string",
            "bool" => "boolean",
            _ => "string"
        };
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToLowerInvariant(name[0]) + name[1..];
    }

    [GeneratedRegex(@"\{(\w+)(?::(\w+))?\}")]
    private static partial Regex ParamPattern();
}
