using System.Collections;
using System.Reflection;
using System.Text;

namespace Impulse.CodeGen;

/// <summary>
/// Generates TypeScript interfaces from C# types.
/// </summary>
public sealed class TypeScriptGenerator
{
    private readonly TypeScriptGeneratorOptions _options;
    private readonly HashSet<Type> _processedTypes = new();
    private readonly Queue<Type> _pendingTypes = new();

    public TypeScriptGenerator(TypeScriptGeneratorOptions? options = null)
    {
        _options = options ?? new TypeScriptGeneratorOptions();
    }

    /// <summary>
    /// Generates TypeScript interfaces for the given types.
    /// </summary>
    public string Generate(IEnumerable<Type> types)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// This file is auto-generated by Impulse.CodeGen");
        sb.AppendLine("// Do not edit manually");
        sb.AppendLine();

        foreach (var type in types)
        {
            _pendingTypes.Enqueue(type);
        }

        while (_pendingTypes.Count > 0)
        {
            var type = _pendingTypes.Dequeue();
            if (_processedTypes.Contains(type) || IsBuiltInType(type))
            {
                continue;
            }

            _processedTypes.Add(type);

            if (type.IsEnum)
            {
                sb.AppendLine(GenerateEnum(type));
            }
            else if (type.IsClass || type.IsValueType && !type.IsPrimitive)
            {
                sb.AppendLine(GenerateInterface(type));
            }
        }

        return sb.ToString();
    }

    private string GenerateInterface(Type type)
    {
        var sb = new StringBuilder();
        var typeName = GetTypeScriptTypeName(type, includeGenerics: false);

        sb.AppendLine($"export interface {typeName} {{");

        var properties = type.GetProperties(BindingFlags.Public | BindingFlags.Instance);
        foreach (var prop in properties)
        {
            var propName = ToCamelCase(prop.Name);
            var propType = GetTypeScriptType(prop.PropertyType);
            var isNullable = IsNullable(prop.PropertyType) || IsNullableReferenceType(prop);

            sb.AppendLine($"  {propName}{(isNullable ? "?" : "")}: {propType};");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private string GenerateEnum(Type type)
    {
        var sb = new StringBuilder();
        var typeName = GetTypeScriptTypeName(type, includeGenerics: false);

        var values = Enum.GetNames(type)
            .Select(name => $"'{ToCamelCase(name)}'");

        sb.AppendLine($"export type {typeName} = {string.Join(" | ", values)};");
        return sb.ToString();
    }

    /// <summary>
    /// Gets the TypeScript type representation for a C# type.
    /// </summary>
    public string GetTypeScriptType(Type type)
    {
        // Handle nullable value types
        var underlyingType = Nullable.GetUnderlyingType(type);
        if (underlyingType is not null)
        {
            return $"{GetTypeScriptType(underlyingType)} | null";
        }

        // Handle primitives
        if (type == typeof(int) || type == typeof(long) || type == typeof(short) ||
            type == typeof(byte) || type == typeof(double) || type == typeof(float) ||
            type == typeof(decimal))
        {
            return "number";
        }

        if (type == typeof(string) || type == typeof(Guid))
        {
            return "string";
        }

        if (type == typeof(bool))
        {
            return "boolean";
        }

        if (type == typeof(DateTime) || type == typeof(DateTimeOffset) ||
            type == typeof(DateOnly) || type == typeof(TimeOnly))
        {
            return "string"; // ISO 8601 format
        }

        // Handle arrays
        if (type.IsArray)
        {
            var elementType = type.GetElementType()!;
            return $"readonly {GetTypeScriptType(elementType)}[]";
        }

        // Handle generic collections
        if (type.IsGenericType)
        {
            var genericDef = type.GetGenericTypeDefinition();
            var genericArgs = type.GetGenericArguments();

            // IReadOnlyList, IEnumerable, List, etc. -> readonly T[]
            if (typeof(IEnumerable).IsAssignableFrom(type) && genericArgs.Length == 1)
            {
                return $"readonly {GetTypeScriptType(genericArgs[0])}[]";
            }

            // Dictionary -> Record<K, V>
            if (genericDef == typeof(Dictionary<,>) ||
                genericDef == typeof(IDictionary<,>) ||
                genericDef == typeof(IReadOnlyDictionary<,>))
            {
                return $"Record<{GetTypeScriptType(genericArgs[0])}, {GetTypeScriptType(genericArgs[1])}>";
            }
        }

        // Handle enums
        if (type.IsEnum)
        {
            QueueType(type);
            return GetTypeScriptTypeName(type, includeGenerics: false);
        }

        // Handle complex types
        if (type.IsClass || type.IsValueType)
        {
            QueueType(type);
            return GetTypeScriptTypeName(type, includeGenerics: false);
        }

        return "unknown";
    }

    private string GetTypeScriptTypeName(Type type, bool includeGenerics)
    {
        var name = type.Name;

        // Remove generic backtick notation
        var backtickIndex = name.IndexOf('`');
        if (backtickIndex > 0)
        {
            name = name[..backtickIndex];
        }

        if (includeGenerics && type.IsGenericType)
        {
            var genericArgs = type.GetGenericArguments()
                .Select(t => GetTypeScriptType(t));
            name += $"<{string.Join(", ", genericArgs)}>";
        }

        return name;
    }

    private void QueueType(Type type)
    {
        if (!_processedTypes.Contains(type) && !IsBuiltInType(type))
        {
            _pendingTypes.Enqueue(type);
        }
    }

    private static bool IsBuiltInType(Type type)
    {
        return type.IsPrimitive ||
               type == typeof(string) ||
               type == typeof(decimal) ||
               type == typeof(DateTime) ||
               type == typeof(DateTimeOffset) ||
               type == typeof(DateOnly) ||
               type == typeof(TimeOnly) ||
               type == typeof(Guid) ||
               type == typeof(object);
    }

    private static bool IsNullable(Type type)
    {
        return Nullable.GetUnderlyingType(type) is not null;
    }

    private static bool IsNullableReferenceType(PropertyInfo prop)
    {
        var nullableContext = prop.DeclaringType?
            .GetCustomAttribute<System.Runtime.CompilerServices.NullableContextAttribute>();
        var nullableAttribute = prop
            .GetCustomAttribute<System.Runtime.CompilerServices.NullableAttribute>();

        if (nullableAttribute?.NullableFlags.Length > 0)
        {
            return nullableAttribute.NullableFlags[0] == 2;
        }

        return nullableContext?.Flag == 2;
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToLowerInvariant(name[0]) + name[1..];
    }
}

/// <summary>
/// Options for TypeScript generation.
/// </summary>
public sealed class TypeScriptGeneratorOptions
{
    public bool UseReadonlyArrays { get; set; } = true;
    public bool GenerateEnumsAsUnions { get; set; } = true;
}
