// Generated by Shalimar.Razor - DO NOT EDIT
import React from 'react';

export interface MyProfileProps {
  AvatarUrl: any;
  FullName: any;
  JobTitle: any;
  ProjectCount: any;
  FollowerCount: any;
  Rating: any;
  IsVerified: any;
  Bio: any;
  Skills: any;
}

export function MyProfile(props: MyProfileProps) {
  return (
    <div className="profile-card">
    <div className="profile-header">
    <img className="avatar" src="{props.AvatarUrl}" alt="Profile" />
    <h1>{props.FullName}</h1>
    <p className="title">{props.JobTitle}</p>
    </div>
    <div className="profile-stats">
    <div className="stat">
    <span className="stat-value">{props.ProjectCount}</span>
    <span className="stat-label">Projects</span>
    </div>
    <div className="stat">
    <span className="stat-value">{props.FollowerCount}</span>
    <span className="stat-label">Followers</span>
    </div>
    <div className="stat">
    <span className="stat-value">{props.Rating}</span>
    <span className="stat-label">Rating</span>
    </div>
    </div>
    {(props.IsVerified) && (
    <div className="verified-badge">
    <span>Verified Account</span>
    </div>
    )}
    <div className="profile-bio">
    <h2>About</h2>
    <p>{props.Bio}</p>
    </div>
    <div className="profile-skills">
    <h2>Skills</h2>
    <ul>
    {props.Skills.map((skill) => (
    <li className="skill-tag">@skill</li>
    ))}
    </ul>
    </div>
    <div className="profile-actions">
    <button className="btn btn-primary" onClick={OnFollow}>
    Follow
    </button>
    <button className="btn btn-secondary" onClick={OnMessage}>
    Message
    </button>
    </div>
    </div>
  );
}
