// Generated by Shalimar.Razor - DO NOT EDIT
import React from 'react';
import { Icon } from './Icon';
import { MedRow } from './MedRow';

export interface ResidentCardProps {
  Name: string;
  RoomNumber: string;
  IsHighRisk: boolean;
  Medications: Medication[];
  Id: string;
}

export interface ResidentCardHandlers {
  OnViewDetails: () => void;
  OnPrint: () => void;
  HandleAdminister: (med: Medication) => void;
  HandleRefuse: (med: Medication) => void;
}

export function ResidentCard(props: ResidentCardProps & ResidentCardHandlers) {
  return (
    <div className="card resident-card">
      <header className="card-header">
        <h1>{props.Name}</h1>
        <span className="room-number">Room {props.RoomNumber}</span>
      </header>

      {props.IsHighRisk && (
        <div className="alert alert-warning">
          <Icon name="warning" />
          High Fall Risk
        </div>
      )}

      <section className="medications">
        <h2>Current Medications</h2>
        <ul>
          {props.Medications.map((med) => (
            <MedRow
              medication={med}
              onAdminister={props.HandleAdminister}
              onRefuse={props.HandleRefuse}
            />
          ))}
        </ul>
      </section>

      <footer className="card-actions">
        <button className="btn btn-primary" onClick={props.OnViewDetails}>
          View Details
        </button>
        <button className="btn btn-secondary" onClick={props.OnPrint}>
          Print MAR
        </button>
      </footer>
    </div>
  );
}
