using System.Text;
using Impulse.CodeGen.Ast;

namespace Impulse.CodeGen;

/// <summary>
/// Emits React Query mutation hooks from endpoint metadata.
/// </summary>
public class MutationEmitter
{
    /// <summary>
    /// Emit a complete mutations file.
    /// </summary>
    public string EmitFile(MutationsFile file)
    {
        var sb = new StringBuilder();

        // Header and imports
        sb.AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        sb.AppendLine("import { useMutation } from '@tanstack/react-query';");
        sb.AppendLine("import { useRouter } from '@tanstack/react-router';");
        sb.AppendLine("import type { ImpulseContext } from '@impulse/react';");
        sb.AppendLine("import { RoutePaths } from './routePaths';");
        sb.AppendLine("import * as Types from './types';");
        sb.AppendLine("import * as Schemas from './validation';");
        sb.AppendLine();

        // Generate each mutation hook
        foreach (var mutation in file.Mutations)
        {
            sb.Append(EmitMutation(mutation));
            sb.AppendLine();
        }

        return sb.ToString().TrimEnd();
    }

    /// <summary>
    /// Emit a single mutation hook.
    /// </summary>
    public string EmitMutation(MutationInfo mutation)
    {
        var sb = new StringBuilder();
        var hookName = $"use{mutation.Name}Mutation";
        var schemaName = $"{mutation.RequestType}Schema";

        sb.AppendLine($"/**");
        sb.AppendLine($" * Mutation hook for {mutation.Name}");
        sb.AppendLine($" * {mutation.Method} {mutation.Route}");
        sb.AppendLine($" */");
        sb.AppendLine($"export function {hookName}(ctx: ImpulseContext) {{");

        if (mutation.InvalidatesQueries)
        {
            sb.AppendLine("  const router = useRouter();");
            sb.AppendLine();
        }

        sb.AppendLine("  return useMutation({");
        sb.AppendLine($"    mutationFn: async (data: Types.{mutation.RequestType}) => {{");
        sb.AppendLine($"      // Validate with Zod before sending");
        sb.AppendLine($"      const validated = Schemas.{schemaName}.parse(data);");
        sb.AppendLine($"      return ctx.impulseMutate<Types.{mutation.RequestType}, Types.{mutation.ResponseType}>(");
        sb.AppendLine($"        RoutePaths.{mutation.Name},");
        sb.AppendLine($"        validated,");
        sb.AppendLine($"        '{mutation.Method}'");
        sb.AppendLine("      );");
        sb.AppendLine("    },");

        if (mutation.InvalidatesQueries)
        {
            sb.AppendLine("    onSuccess: async () => {");
            sb.AppendLine("      // Invalidate and refetch related queries");
            sb.AppendLine("      await router.invalidate();");
            sb.AppendLine("    },");
        }

        sb.AppendLine("  });");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
