using System.Text;
using Impulse.CodeGen.Ast;

namespace Impulse.CodeGen;

/// <summary>
/// Emits route paths TypeScript file from endpoint routes.
/// </summary>
public class RouteEmitter
{
    /// <summary>
    /// Emit a complete route paths file.
    /// </summary>
    public string EmitFile(RouteFile file)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        sb.AppendLine();
        sb.AppendLine("export const RoutePaths = {");

        foreach (var route in file.Routes)
        {
            // Convert route params like {id} to :id for TanStack Router compatibility
            var routePath = ConvertRouteParams(route.Route);
            sb.AppendLine($"  {route.Name}: '{routePath}',");
        }

        sb.AppendLine("} as const;");
        sb.AppendLine();
        sb.AppendLine("export type RoutePath = (typeof RoutePaths)[keyof typeof RoutePaths];");

        return sb.ToString().TrimEnd();
    }

    /// <summary>
    /// Emit a route builder for parameterized routes.
    /// </summary>
    public string EmitRouteBuilders(RouteFile file)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        sb.AppendLine();
        sb.AppendLine("import { RoutePaths } from './routePaths';");
        sb.AppendLine();

        foreach (var route in file.Routes)
        {
            var paramNames = ExtractParams(route.Route);
            if (paramNames.Count == 0) continue;

            var fnName = $"build{route.Name}Route";
            var paramList = string.Join(", ", paramNames.Select(p => $"{p}: string | number"));
            var template = route.Route;

            // Build the route with template substitution
            foreach (var param in paramNames)
            {
                template = template.Replace($"{{{param}}}", $"${{{param}}}");
            }

            sb.AppendLine($"export function {fnName}({paramList}): string {{");
            sb.AppendLine($"  return `{template}`;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString().TrimEnd();
    }

    private static string ConvertRouteParams(string route)
    {
        // Convert {param} to :param for TanStack Router
        return System.Text.RegularExpressions.Regex.Replace(
            route,
            @"\{(\w+)\}",
            ":$1");
    }

    private static List<string> ExtractParams(string route)
    {
        var matches = System.Text.RegularExpressions.Regex.Matches(route, @"\{(\w+)\}");
        return matches.Select(m => m.Groups[1].Value).ToList();
    }
}
