using System.Text;
using Impulse.CodeGen.Ast;

namespace Impulse.CodeGen;

/// <summary>
/// Emits TypeScript code from AST.
/// </summary>
public class TsEmitter
{
    /// <summary>
    /// Emit a TypeScript type to string.
    /// </summary>
    public string EmitType(TsType type)
    {
        return type switch
        {
            TsString => "string",
            TsNumber => "number",
            TsBoolean => "boolean",
            TsNull => "null",
            TsUndefined => "undefined",
            TsUnknown => "unknown",
            TsArray a => $"readonly {EmitType(a.Element)}[]",
            TsRecord r => $"Record<{EmitType(r.KeyType)}, {EmitType(r.ValueType)}>",
            TsRef r => r.Name,
            TsUnion u => string.Join(" | ", u.Types.Select(EmitType)),
            _ => "unknown"
        };
    }

    /// <summary>
    /// Emit a TypeScript interface.
    /// </summary>
    public string EmitInterface(TsInterface iface)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"export interface {iface.Name} {{");

        foreach (var prop in iface.Properties)
        {
            var optional = prop.IsOptional ? "?" : "";
            sb.AppendLine($"  {prop.Name}{optional}: {EmitType(prop.Type)};");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emit a TypeScript enum.
    /// </summary>
    public string EmitEnum(TsEnum enumNode)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"export enum {enumNode.Name} {{");

        foreach (var member in enumNode.Members)
        {
            sb.AppendLine($"  {member.Name} = {member.Value},");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emit a complete TypeScript types file.
    /// </summary>
    public string EmitFile(IEnumerable<TsEnum> enums, IEnumerable<TsInterface> interfaces)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        sb.AppendLine();

        foreach (var enumNode in enums)
        {
            sb.Append(EmitEnum(enumNode));
            sb.AppendLine();
        }

        foreach (var iface in interfaces)
        {
            sb.Append(EmitInterface(iface));
            sb.AppendLine();
        }

        return sb.ToString().TrimEnd();
    }
}
