using System.Text;
using Impulse.CodeGen.Ast;

namespace Impulse.CodeGen;

/// <summary>
/// Emits Zod schema code from AST.
/// </summary>
public class ZodEmitter
{
    /// <summary>
    /// Emit a Zod type to string.
    /// </summary>
    public string EmitType(ZodType type)
    {
        return type switch
        {
            ZodString s => EmitString(s),
            ZodNumber n => EmitNumber(n),
            ZodBoolean => "z.boolean()",
            ZodArray a => EmitArray(a),
            ZodRecord r => $"z.record({EmitType(r.KeyType)}, {EmitType(r.ValueType)})",
            ZodObject o => EmitObject(o),
            ZodNativeEnum e => $"z.nativeEnum({e.EnumName})",
            ZodRef r => r.SchemaName,
            ZodNullable n => $"{EmitType(n.Inner)}.nullable()",
            ZodOptional o => $"{EmitType(o.Inner)}.optional()",
            _ => "z.unknown()"
        };
    }

    private string EmitString(ZodString str)
    {
        var sb = new StringBuilder("z.string()");
        foreach (var validator in str.Validators)
        {
            sb.Append(EmitValidator(validator));
        }
        return sb.ToString();
    }

    private string EmitNumber(ZodNumber num)
    {
        var sb = new StringBuilder("z.number()");
        foreach (var validator in num.Validators)
        {
            sb.Append(EmitValidator(validator));
        }
        return sb.ToString();
    }

    private string EmitArray(ZodArray arr)
    {
        var sb = new StringBuilder($"z.array({EmitType(arr.Element)})");
        foreach (var validator in arr.Validators)
        {
            sb.Append(EmitValidator(validator));
        }
        return sb.ToString();
    }

    private string EmitObject(ZodObject obj)
    {
        if (obj.Properties.Count == 0)
            return "z.object({})";

        var sb = new StringBuilder("z.object({\n");
        foreach (var prop in obj.Properties)
        {
            sb.Append($"  {prop.Name}: {EmitType(prop.Type)}");
            if (prop.IsOptional)
            {
                sb.Append(".optional()");
            }
            sb.AppendLine(",");
        }
        sb.Append("})");
        return sb.ToString();
    }

    private string EmitValidator(ZodValidator validator)
    {
        return validator switch
        {
            ZodMin m => m.Message != null ? $".min({m.Value}, '{m.Message}')" : $".min({m.Value})",
            ZodMax m => m.Message != null ? $".max({m.Value}, '{m.Message}')" : $".max({m.Value})",
            ZodEmail e => e.Message != null ? $".email('{e.Message}')" : ".email()",
            ZodUrl u => u.Message != null ? $".url('{u.Message}')" : ".url()",
            ZodUuid u => u.Message != null ? $".uuid('{u.Message}')" : ".uuid()",
            ZodInt i => i.Message != null ? $".int('{i.Message}')" : ".int()",
            ZodPositive p => p.Message != null ? $".positive('{p.Message}')" : ".positive()",
            ZodNegative n => n.Message != null ? $".negative('{n.Message}')" : ".negative()",
            ZodTrim => ".trim()",
            ZodDatetime d => d.Message != null ? $".datetime('{d.Message}')" : ".datetime()",
            ZodRegex r => r.Message != null ? $".regex(/{r.Pattern}/, '{r.Message}')" : $".regex(/{r.Pattern}/)",
            _ => ""
        };
    }

    /// <summary>
    /// Emit a named schema export.
    /// </summary>
    public string EmitSchema(ZodSchema schema)
    {
        return $"export const {schema.Name}Schema = {EmitType(schema.Shape)};";
    }

    /// <summary>
    /// Emit a complete Zod file.
    /// </summary>
    public string EmitFile(ZodFile file)
    {
        var sb = new StringBuilder();

        // Imports
        sb.AppendLine("// Auto-generated by impulse-gen - DO NOT EDIT");
        sb.AppendLine("import { z } from 'zod';");

        // Collect enum imports
        var enums = CollectEnumRefs(file);
        if (enums.Count > 0)
        {
            sb.AppendLine($"import {{ {string.Join(", ", enums)} }} from './types';");
        }

        sb.AppendLine();

        // Schemas
        foreach (var schema in file.Schemas)
        {
            sb.AppendLine(EmitSchema(schema));
            sb.AppendLine();
        }

        return sb.ToString().TrimEnd();
    }

    private HashSet<string> CollectEnumRefs(ZodFile file)
    {
        var enums = new HashSet<string>();
        foreach (var schema in file.Schemas)
        {
            CollectEnumRefs(schema.Shape, enums);
        }
        return enums;
    }

    private void CollectEnumRefs(ZodType type, HashSet<string> enums)
    {
        switch (type)
        {
            case ZodNativeEnum e:
                enums.Add(e.EnumName);
                break;
            case ZodObject o:
                foreach (var prop in o.Properties)
                    CollectEnumRefs(prop.Type, enums);
                break;
            case ZodArray a:
                CollectEnumRefs(a.Element, enums);
                break;
            case ZodNullable n:
                CollectEnumRefs(n.Inner, enums);
                break;
            case ZodOptional o:
                CollectEnumRefs(o.Inner, enums);
                break;
        }
    }
}
